import { config } from "dotenv";
config(); // Load environment variables

import { PrismaClient } from "@prisma/client";
import { PrismaPg } from "@prisma/adapter-pg";
import { Pool } from "pg";

const pool = new Pool({
  host: process.env.DATABASE_HOST || "localhost",
  port: parseInt(process.env.DATABASE_PORT || "5432"),
  user: process.env.DATABASE_USER || "postgres",
  password: process.env.DATABASE_PASSWORD,
  database: process.env.DATABASE_NAME || "llcpad",
});
const adapter = new PrismaPg(pool);
const prisma = new PrismaClient({ adapter });

// 12 Built-in Footer Presets
const footerPresets = [
  // ============ MINIMAL CATEGORY ============
  {
    name: "Clean Minimal",
    description: "Simple, clean footer with centered logo and inline links. Perfect for modern landing pages.",
    category: "minimal",
    thumbnail: "/presets/footer/clean-minimal.png",
    tags: ["minimal", "centered", "clean", "light"],
    colorPalette: {
      primary: "#000000",
      secondary: "#6b7280",
      accent: "#2563eb",
      text: "#374151",
      bg: "#ffffff",
    },
    config: {
      layout: "CENTERED",
      columns: 4,
      bgType: "solid",
      bgColor: "#ffffff",
      textColor: "#6b7280",
      headingColor: "#111827",
      linkColor: "#374151",
      linkHoverColor: "#2563eb",
      headingSize: "sm",
      headingWeight: "semibold",
      headingStyle: "normal",
      socialShape: "circle",
      socialSize: "md",
      socialColorMode: "monochrome",
      socialHoverEffect: "scale",
      dividerStyle: "solid",
      dividerColor: "#e5e7eb",
      topBorderStyle: "none",
      shadow: "none",
      paddingTop: 48,
      paddingBottom: 32,
      bottomBarLayout: "centered",
    },
  },
  {
    name: "Dark Elegance",
    description: "Sophisticated dark footer with subtle accents. Great for premium brands.",
    category: "minimal",
    thumbnail: "/presets/footer/dark-elegance.png",
    tags: ["minimal", "dark", "elegant", "premium"],
    colorPalette: {
      primary: "#ffffff",
      secondary: "#9ca3af",
      accent: "#f59e0b",
      text: "#9ca3af",
      bg: "#111827",
    },
    config: {
      layout: "MINIMAL",
      columns: 4,
      bgType: "solid",
      bgColor: "#111827",
      textColor: "#9ca3af",
      headingColor: "#ffffff",
      linkColor: "#d1d5db",
      linkHoverColor: "#f59e0b",
      headingSize: "sm",
      headingWeight: "medium",
      headingStyle: "uppercase",
      socialShape: "rounded",
      socialSize: "md",
      socialColorMode: "monochrome",
      socialHoverEffect: "glow",
      dividerStyle: "solid",
      dividerColor: "#374151",
      topBorderStyle: "gradient",
      topBorderHeight: 2,
      topBorderColor: "#f59e0b",
      shadow: "none",
      paddingTop: 32,
      paddingBottom: 24,
      bottomBarLayout: "split",
    },
  },

  // ============ PROFESSIONAL CATEGORY ============
  {
    name: "Corporate Standard",
    description: "Classic multi-column layout for professional businesses. Clean and organized.",
    category: "professional",
    thumbnail: "/presets/footer/corporate-standard.png",
    tags: ["professional", "multi-column", "corporate", "light"],
    colorPalette: {
      primary: "#1e40af",
      secondary: "#64748b",
      accent: "#3b82f6",
      text: "#475569",
      bg: "#f8fafc",
    },
    config: {
      layout: "MULTI_COLUMN",
      columns: 4,
      bgType: "solid",
      bgColor: "#f8fafc",
      textColor: "#64748b",
      headingColor: "#1e293b",
      linkColor: "#475569",
      linkHoverColor: "#3b82f6",
      headingSize: "sm",
      headingWeight: "semibold",
      headingStyle: "normal",
      socialShape: "square",
      socialSize: "md",
      socialColorMode: "brand",
      socialHoverEffect: "lift",
      dividerStyle: "solid",
      dividerColor: "#e2e8f0",
      topBorderStyle: "solid",
      topBorderHeight: 1,
      topBorderColor: "#e2e8f0",
      shadow: "none",
      paddingTop: 64,
      paddingBottom: 40,
      bottomBarLayout: "split",
    },
  },
  {
    name: "Enterprise Dark",
    description: "Full mega-footer style for large enterprise websites. Comprehensive sitemap.",
    category: "professional",
    thumbnail: "/presets/footer/enterprise-dark.png",
    tags: ["professional", "mega", "dark", "enterprise"],
    colorPalette: {
      primary: "#e2e8f0",
      secondary: "#94a3b8",
      accent: "#22d3ee",
      text: "#94a3b8",
      bg: "#0f172a",
    },
    config: {
      layout: "MULTI_COLUMN",
      columns: 5,
      bgType: "solid",
      bgColor: "#0f172a",
      textColor: "#94a3b8",
      headingColor: "#e2e8f0",
      linkColor: "#cbd5e1",
      linkHoverColor: "#22d3ee",
      accentColor: "#22d3ee",
      headingSize: "sm",
      headingWeight: "semibold",
      headingStyle: "uppercase",
      socialShape: "circle",
      socialSize: "lg",
      socialColorMode: "brand",
      socialHoverEffect: "scale",
      dividerStyle: "solid",
      dividerColor: "#22d3ee",
      linkHoverEffect: "color",
      topBorderStyle: "none",
      shadow: "none",
      paddingTop: 64,
      paddingBottom: 40,
      bottomBarLayout: "split",
      newsletterEnabled: true,
      // Animation - Professional fade-up for enterprise feel
      enableAnimations: true,
      entranceAnimation: "fade-up",
      animationDuration: 400,
      // Widgets configuration
      widgets: [
        {
          type: "BRAND",
          title: "",
          showTitle: false,
          column: 1,
          sortOrder: 0,
          content: {
            tagline: "Your Business Formation Partner",
            showContact: false,
            showSocial: false,
          },
        },
        {
          type: "NEWSLETTER",
          title: "Stay Updated",
          showTitle: true,
          column: 1,
          sortOrder: 1,
          content: {
            subtitle: "Get the latest updates and tips",
            buttonText: "Subscribe",
            style: "inline",
          },
        },
        {
          type: "SOCIAL",
          title: "Follow Us",
          showTitle: true,
          column: 1,
          sortOrder: 2,
          content: {},
        },
        {
          type: "LINKS",
          title: "Company",
          showTitle: true,
          column: 2,
          sortOrder: 0,
          menuItems: [
            { label: "About Us", url: "/about" },
            { label: "Our Team", url: "/team" },
            { label: "Careers", url: "/careers" },
            { label: "Press", url: "/press" },
          ],
        },
        {
          type: "LINKS",
          title: "Services",
          showTitle: true,
          column: 3,
          sortOrder: 0,
          menuItems: [
            { label: "LLC Formation", url: "/services/llc-formation" },
            { label: "EIN Application", url: "/services/ein-application" },
            { label: "Registered Agent", url: "/services/registered-agent" },
            { label: "Business Banking", url: "/services/business-banking" },
          ],
        },
        {
          type: "LINKS",
          title: "Resources",
          showTitle: true,
          column: 4,
          sortOrder: 0,
          menuItems: [
            { label: "Blog", url: "/blog" },
            { label: "Guides", url: "/guides" },
            { label: "State Fees", url: "/state-fees" },
            { label: "FAQs", url: "/faq" },
          ],
        },
        {
          type: "LINKS",
          title: "Support",
          showTitle: true,
          column: 5,
          sortOrder: 0,
          menuItems: [
            { label: "Contact Us", url: "/contact" },
            { label: "Help Center", url: "/help" },
            { label: "Live Chat", url: "/chat" },
            { label: "Support Tickets", url: "/dashboard/tickets" },
          ],
        },
      ],
      bottomLinks: [
        { label: "Privacy Policy", url: "/privacy" },
        { label: "Terms of Service", url: "/terms" },
        { label: "Refund Policy", url: "/refund-policy" },
        { label: "Disclaimer", url: "/disclaimer" },
      ],
    },
  },

  // ============ MODERN CATEGORY ============
  {
    name: "SaaS Modern",
    description: "Modern gradient footer perfect for SaaS and tech startups.",
    category: "modern",
    thumbnail: "/presets/footer/saas-modern.png",
    tags: ["modern", "gradient", "saas", "tech"],
    colorPalette: {
      primary: "#ffffff",
      secondary: "#c7d2fe",
      accent: "#818cf8",
      text: "#e0e7ff",
      bg: "#4338ca",
    },
    config: {
      layout: "STACKED",
      columns: 4,
      bgType: "gradient",
      bgGradient: {
        type: "linear",
        colors: [
          { color: "#4338ca", position: 0 },
          { color: "#6366f1", position: 50 },
          { color: "#818cf8", position: 100 },
        ],
        angle: 135,
      },
      textColor: "#e0e7ff",
      headingColor: "#ffffff",
      linkColor: "#c7d2fe",
      linkHoverColor: "#ffffff",
      headingSize: "base",
      headingWeight: "bold",
      headingStyle: "normal",
      socialShape: "pill",
      socialSize: "md",
      socialColorMode: "monochrome",
      socialHoverEffect: "scale",
      dividerStyle: "none",
      topBorderStyle: "none",
      shadow: "none",
      paddingTop: 64,
      paddingBottom: 40,
      bottomBarLayout: "centered",
      enableAnimations: true,
      entranceAnimation: "fade-up",
      animationDuration: 400,
    },
  },
  {
    name: "Glassmorphism",
    description: "Trendy frosted glass effect with blur and transparency.",
    category: "modern",
    thumbnail: "/presets/footer/glassmorphism.png",
    tags: ["modern", "glass", "blur", "trendy"],
    colorPalette: {
      primary: "#1e293b",
      secondary: "#64748b",
      accent: "#0ea5e9",
      text: "#475569",
      bg: "rgba(255,255,255,0.8)",
    },
    config: {
      layout: "MULTI_COLUMN",
      columns: 4,
      bgType: "solid",
      bgColor: "rgba(255,255,255,0.85)",
      textColor: "#64748b",
      headingColor: "#1e293b",
      linkColor: "#475569",
      linkHoverColor: "#0ea5e9",
      headingSize: "sm",
      headingWeight: "semibold",
      headingStyle: "normal",
      socialShape: "rounded",
      socialSize: "md",
      socialColorMode: "brand",
      socialHoverEffect: "lift",
      dividerStyle: "none",
      topBorderStyle: "solid",
      topBorderHeight: 1,
      topBorderColor: "rgba(255,255,255,0.5)",
      shadow: "lg",
      borderRadius: 24,
      paddingTop: 48,
      paddingBottom: 32,
      bottomBarLayout: "split",
    },
  },
  {
    name: "Neon Tech",
    description: "Cyberpunk-inspired dark theme with neon accents and glow effects.",
    category: "modern",
    thumbnail: "/presets/footer/neon-tech.png",
    tags: ["modern", "neon", "dark", "cyberpunk"],
    colorPalette: {
      primary: "#f0abfc",
      secondary: "#a855f7",
      accent: "#22d3ee",
      text: "#c084fc",
      bg: "#0c0a1d",
    },
    config: {
      layout: "MEGA",
      columns: 5,
      bgType: "solid",
      bgColor: "#0c0a1d",
      textColor: "#a78bfa",
      headingColor: "#f0abfc",
      linkColor: "#c084fc",
      linkHoverColor: "#22d3ee",
      headingSize: "sm",
      headingWeight: "bold",
      headingStyle: "uppercase",
      socialShape: "square",
      socialSize: "lg",
      socialColorMode: "accent",
      socialHoverEffect: "glow",
      dividerStyle: "gradient",
      dividerColor: "#7c3aed",
      topBorderStyle: "gradient",
      topBorderHeight: 3,
      topBorderColor: "#22d3ee",
      shadow: "none",
      paddingTop: 64,
      paddingBottom: 40,
      bottomBarLayout: "split",
      enableAnimations: true,
      entranceAnimation: "fade-in",
      animationDuration: 300,
    },
  },

  // ============ CREATIVE CATEGORY ============
  {
    name: "Colorful Blocks",
    description: "Playful design with each column having a different subtle background.",
    category: "creative",
    thumbnail: "/presets/footer/colorful-blocks.png",
    tags: ["creative", "colorful", "playful", "fun"],
    colorPalette: {
      primary: "#1e293b",
      secondary: "#64748b",
      accent: "#f472b6",
      text: "#475569",
      bg: "#fef3c7",
    },
    config: {
      layout: "MULTI_COLUMN",
      columns: 4,
      bgType: "pattern",
      bgColor: "#fef3c7",
      bgPattern: "dots",
      bgPatternColor: "#f59e0b",
      bgPatternOpacity: 0.1,
      textColor: "#78716c",
      headingColor: "#292524",
      linkColor: "#57534e",
      linkHoverColor: "#f472b6",
      headingSize: "base",
      headingWeight: "bold",
      headingStyle: "normal",
      socialShape: "circle",
      socialSize: "lg",
      socialColorMode: "brand",
      socialHoverEffect: "rotate",
      dividerStyle: "dashed",
      dividerColor: "#fcd34d",
      topBorderStyle: "wave",
      topBorderHeight: 8,
      topBorderColor: "#f472b6",
      shadow: "none",
      paddingTop: 56,
      paddingBottom: 40,
      bottomBarLayout: "centered",
    },
  },

  // ============ INDUSTRY CATEGORY ============
  {
    name: "E-commerce Pro",
    description: "Feature-rich footer for e-commerce with trust badges and payment methods.",
    category: "industry",
    thumbnail: "/presets/footer/ecommerce-pro.png",
    tags: ["industry", "ecommerce", "trust", "payments"],
    colorPalette: {
      primary: "#059669",
      secondary: "#6b7280",
      accent: "#10b981",
      text: "#4b5563",
      bg: "#f9fafb",
    },
    config: {
      layout: "MEGA_PLUS",
      columns: 5,
      bgType: "solid",
      bgColor: "#f9fafb",
      textColor: "#6b7280",
      headingColor: "#111827",
      linkColor: "#4b5563",
      linkHoverColor: "#059669",
      headingSize: "sm",
      headingWeight: "semibold",
      headingStyle: "normal",
      socialShape: "rounded",
      socialSize: "md",
      socialColorMode: "brand",
      socialHoverEffect: "scale",
      dividerStyle: "solid",
      dividerColor: "#e5e7eb",
      topBorderStyle: "solid",
      topBorderHeight: 4,
      topBorderColor: "#059669",
      shadow: "sm",
      paddingTop: 64,
      paddingBottom: 48,
      bottomBarLayout: "stacked",
      showTrustBadges: true,
    },
  },
  {
    name: "Legal Services",
    description: "Professional and trustworthy footer for legal and business services.",
    category: "industry",
    thumbnail: "/presets/footer/legal-services.png",
    tags: ["industry", "legal", "professional", "trust"],
    colorPalette: {
      primary: "#1e3a5f",
      secondary: "#64748b",
      accent: "#0369a1",
      text: "#475569",
      bg: "#ffffff",
    },
    config: {
      layout: "MULTI_COLUMN",
      columns: 4,
      bgType: "solid",
      bgColor: "#ffffff",
      textColor: "#64748b",
      headingColor: "#1e3a5f",
      linkColor: "#475569",
      linkHoverColor: "#0369a1",
      headingSize: "sm",
      headingWeight: "semibold",
      headingStyle: "normal",
      socialShape: "square",
      socialSize: "sm",
      socialColorMode: "monochrome",
      socialHoverEffect: "lift",
      dividerStyle: "solid",
      dividerColor: "#e2e8f0",
      topBorderStyle: "solid",
      topBorderHeight: 4,
      topBorderColor: "#1e3a5f",
      shadow: "none",
      paddingTop: 56,
      paddingBottom: 40,
      bottomBarLayout: "split",
    },
  },
  {
    name: "App Launch",
    description: "App-focused footer with prominent download badges and QR code.",
    category: "industry",
    thumbnail: "/presets/footer/app-launch.png",
    tags: ["industry", "app", "mobile", "download"],
    colorPalette: {
      primary: "#7c3aed",
      secondary: "#a78bfa",
      accent: "#8b5cf6",
      text: "#c4b5fd",
      bg: "#1e1b4b",
    },
    config: {
      layout: "APP_FOCUSED",
      columns: 3,
      bgType: "gradient",
      bgGradient: {
        type: "linear",
        colors: [
          { color: "#1e1b4b", position: 0 },
          { color: "#312e81", position: 100 },
        ],
        angle: 180,
      },
      textColor: "#c4b5fd",
      headingColor: "#ffffff",
      linkColor: "#a78bfa",
      linkHoverColor: "#f5f3ff",
      headingSize: "lg",
      headingWeight: "bold",
      headingStyle: "normal",
      socialShape: "circle",
      socialSize: "lg",
      socialColorMode: "accent",
      socialHoverEffect: "scale",
      dividerStyle: "none",
      topBorderStyle: "none",
      shadow: "none",
      paddingTop: 72,
      paddingBottom: 48,
      bottomBarLayout: "centered",
      enableAnimations: true,
      entranceAnimation: "slide-up",
      animationDuration: 400,
    },
  },
  {
    name: "Newsletter First",
    description: "Newsletter-focused footer with large signup form as the hero element.",
    category: "industry",
    thumbnail: "/presets/footer/newsletter-first.png",
    tags: ["industry", "newsletter", "marketing", "cta"],
    colorPalette: {
      primary: "#dc2626",
      secondary: "#6b7280",
      accent: "#ef4444",
      text: "#4b5563",
      bg: "#fef2f2",
    },
    config: {
      layout: "NEWSLETTER_HERO",
      columns: 4,
      bgType: "solid",
      bgColor: "#fef2f2",
      textColor: "#6b7280",
      headingColor: "#1f2937",
      linkColor: "#4b5563",
      linkHoverColor: "#dc2626",
      accentColor: "#dc2626",
      headingSize: "xl",
      headingWeight: "bold",
      headingStyle: "normal",
      socialShape: "circle",
      socialSize: "md",
      socialColorMode: "brand",
      socialHoverEffect: "scale",
      dividerStyle: "solid",
      dividerColor: "#fecaca",
      topBorderStyle: "none",
      shadow: "none",
      paddingTop: 80,
      paddingBottom: 48,
      bottomBarLayout: "split",
      newsletterEnabled: true,
      newsletterTitle: "Stay in the loop",
      newsletterSubtitle: "Get the latest updates, tips, and exclusive offers delivered to your inbox.",
    },
  },
];

export async function seedFooterPresets() {
  console.log("🎨 Seeding footer presets...");

  for (const preset of footerPresets) {
    const existing = await prisma.footerPreset.findFirst({
      where: { name: preset.name, isBuiltIn: true },
    });

    if (existing) {
      // Update existing preset
      await prisma.footerPreset.update({
        where: { id: existing.id },
        data: {
          ...preset,
          isBuiltIn: true,
          isPublic: true,
        },
      });
      console.log(`  ✓ Updated preset: ${preset.name}`);
    } else {
      // Create new preset
      await prisma.footerPreset.create({
        data: {
          ...preset,
          isBuiltIn: true,
          isPublic: true,
        },
      });
      console.log(`  ✓ Created preset: ${preset.name}`);
    }
  }

  console.log(`✅ Seeded ${footerPresets.length} footer presets`);
}

// Run if executed directly
seedFooterPresets()
  .then(async () => {
    console.log("🎉 Footer presets seeding complete!");
    await prisma.$disconnect();
    await pool.end();
    process.exit(0);
  })
  .catch(async (e) => {
    console.error(e);
    await prisma.$disconnect();
    await pool.end();
    process.exit(1);
  });
