import { config } from "dotenv";
config(); // Load environment variables

import { PrismaClient } from "@prisma/client";
import { PrismaPg } from "@prisma/adapter-pg";
import { Pool } from "pg";

const pool = new Pool({
  host: process.env.DATABASE_HOST || "localhost",
  port: parseInt(process.env.DATABASE_PORT || "5432"),
  user: process.env.DATABASE_USER || "postgres",
  password: process.env.DATABASE_PASSWORD,
  database: process.env.DATABASE_NAME || "llcpad",
});
const adapter = new PrismaPg(pool);
const prisma = new PrismaClient({ adapter });

// Helper function to create standard widgets
const createStandardWidgets = (tagline: string = "Your Business Formation Partner") => [
  {
    type: "BRAND",
    title: "",
    showTitle: false,
    column: 1,
    sortOrder: 0,
    content: {
      tagline,
      showContact: false,
      showSocial: false,
    },
  },
  {
    type: "NEWSLETTER",
    title: "Stay Updated",
    showTitle: true,
    column: 1,
    sortOrder: 1,
    content: {
      subtitle: "Get the latest updates and tips",
      buttonText: "Subscribe",
      style: "inline",
    },
  },
  {
    type: "SOCIAL",
    title: "Follow Us",
    showTitle: true,
    column: 1,
    sortOrder: 2,
    content: {},
  },
  {
    type: "LINKS",
    title: "Company",
    showTitle: true,
    column: 2,
    sortOrder: 0,
    menuItems: [
      { label: "About Us", url: "/about" },
      { label: "Our Team", url: "/team" },
      { label: "Careers", url: "/careers" },
      { label: "Press", url: "/press" },
    ],
  },
  {
    type: "LINKS",
    title: "Services",
    showTitle: true,
    column: 3,
    sortOrder: 0,
    menuItems: [
      { label: "LLC Formation", url: "/services/llc-formation" },
      { label: "EIN Application", url: "/services/ein-application" },
      { label: "Registered Agent", url: "/services/registered-agent" },
      { label: "Business Banking", url: "/services/business-banking" },
    ],
  },
  {
    type: "LINKS",
    title: "Resources",
    showTitle: true,
    column: 4,
    sortOrder: 0,
    menuItems: [
      { label: "Blog", url: "/blog" },
      { label: "Guides", url: "/guides" },
      { label: "State Fees", url: "/state-fees" },
      { label: "FAQs", url: "/faq" },
    ],
  },
  {
    type: "LINKS",
    title: "Support",
    showTitle: true,
    column: 5,
    sortOrder: 0,
    menuItems: [
      { label: "Contact Us", url: "/contact" },
      { label: "Help Center", url: "/help" },
      { label: "Live Chat", url: "/chat" },
      { label: "Support Tickets", url: "/dashboard/tickets" },
    ],
  },
];

const standardBottomLinks = [
  { label: "Privacy Policy", url: "/privacy" },
  { label: "Terms of Service", url: "/terms" },
  { label: "Refund Policy", url: "/refund-policy" },
  { label: "Disclaimer", url: "/disclaimer" },
];

// 21 Built-in Footer Presets - All with full control like Enterprise Dark
// Using different layouts: MULTI_COLUMN, STACKED, CENTERED, MINIMAL, MEGA
const footerPresets = [
  // ============ MINIMAL CATEGORY ============
  {
    name: "Clean Minimal",
    description: "Simple centered footer with logo on top. Perfect for landing pages and portfolios.",
    category: "minimal",
    thumbnail: "/presets/footer/clean-minimal.png",
    tags: ["minimal", "centered", "clean", "light"],
    colorPalette: {
      primary: "#000000",
      secondary: "#6b7280",
      accent: "#2563eb",
      text: "#374151",
      bg: "#ffffff",
    },
    config: {
      layout: "CENTERED",  // Centered layout - logo & social on top, links in row below
      columns: 4,
      bgType: "solid",
      bgColor: "#ffffff",
      textColor: "#4b5563",  // Darker for better readability on white
      headingColor: "#111827",
      linkColor: "#374151",
      linkHoverColor: "#2563eb",
      accentColor: "#2563eb",
      borderColor: "#6b7280",  // Darker border for better visibility
      headingSize: "sm",
      headingWeight: "semibold",
      headingStyle: "normal",
      socialShape: "circle",
      socialSize: "md",
      socialColorMode: "monochrome",
      socialHoverEffect: "scale",
      socialBgStyle: "outline",  // Outline for visibility on white
      dividerStyle: "solid",
      dividerColor: "#e5e7eb",
      linkHoverEffect: "color",
      topBorderStyle: "none",
      shadow: "none",
      paddingTop: 48,
      paddingBottom: 32,
      bottomBarLayout: "centered",
      containerWidth: "full",
      containerStyle: "sharp",
      enableAnimations: true,
      entranceAnimation: "fade-up",
      animationDuration: 300,
      newsletterEnabled: true,
      widgets: createStandardWidgets("Simple. Professional. Effective."),
      bottomLinks: standardBottomLinks,
    },
  },
  {
    name: "Dark Elegance",
    description: "Minimal dark footer with amber accents. Brand focused with compact links.",
    category: "minimal",
    thumbnail: "/presets/footer/dark-elegance.png",
    tags: ["minimal", "dark", "elegant", "premium"],
    colorPalette: {
      primary: "#ffffff",
      secondary: "#9ca3af",
      accent: "#f59e0b",
      text: "#9ca3af",
      bg: "#111827",
    },
    config: {
      layout: "MINIMAL",  // Minimal layout - single row with logo, links, social
      columns: 4,
      bgType: "solid",
      bgColor: "#111827",
      textColor: "#d1d5db",  // Lighter for better readability on dark
      headingColor: "#ffffff",
      linkColor: "#d1d5db",
      linkHoverColor: "#f59e0b",
      accentColor: "#f59e0b",
      borderColor: "#4b5563",  // Visible input border on dark bg
      headingSize: "sm",
      headingWeight: "medium",
      headingStyle: "uppercase",
      socialShape: "rounded",
      socialSize: "md",
      socialColorMode: "monochrome",
      socialHoverEffect: "glow",
      socialBgStyle: "outline",
      dividerStyle: "solid",
      dividerColor: "#374151",
      linkHoverEffect: "color",
      topBorderStyle: "gradient",
      topBorderHeight: 2,
      topBorderColor: "#f59e0b",
      shadow: "none",
      paddingTop: 32,
      paddingBottom: 24,
      bottomBarLayout: "split",
      containerWidth: "full",
      containerStyle: "sharp",
      enableAnimations: true,
      entranceAnimation: "fade-up",
      animationDuration: 350,
      newsletterEnabled: true,
      widgets: createStandardWidgets("Elegance in Every Detail"),
      bottomLinks: standardBottomLinks,
    },
  },

  // ============ PROFESSIONAL CATEGORY ============
  {
    name: "Corporate Standard",
    description: "Classic multi-column layout. Professional and organized for business websites.",
    category: "professional",
    thumbnail: "/presets/footer/corporate-standard.png",
    tags: ["professional", "multi-column", "corporate", "light"],
    colorPalette: {
      primary: "#1e40af",
      secondary: "#64748b",
      accent: "#3b82f6",
      text: "#475569",
      bg: "#f8fafc",
    },
    config: {
      layout: "MULTI_COLUMN",  // Standard multi-column
      columns: 5,
      bgType: "solid",
      bgColor: "#f8fafc",
      textColor: "#475569",
      headingColor: "#1e293b",
      linkColor: "#475569",
      linkHoverColor: "#3b82f6",
      accentColor: "#3b82f6",
      borderColor: "#64748b",  // Darker border for better visibility
      headingSize: "sm",
      headingWeight: "semibold",
      headingStyle: "normal",
      socialShape: "square",
      socialSize: "md",
      socialColorMode: "brand",
      socialHoverEffect: "lift",
      socialBgStyle: "subtle",
      dividerStyle: "solid",
      dividerColor: "#e2e8f0",
      linkHoverEffect: "color",
      topBorderStyle: "solid",
      topBorderHeight: 1,
      topBorderColor: "#e2e8f0",
      shadow: "none",
      paddingTop: 64,
      paddingBottom: 40,
      bottomBarLayout: "split",
      containerWidth: "full",
      containerStyle: "sharp",
      enableAnimations: true,
      entranceAnimation: "fade-up",
      animationDuration: 300,
      newsletterEnabled: true,
      widgets: createStandardWidgets("Professional Business Services"),
      bottomLinks: standardBottomLinks,
    },
  },
  {
    name: "Enterprise Dark",
    description: "Full mega-footer style for large enterprise websites. Comprehensive sitemap.",
    category: "professional",
    thumbnail: "/presets/footer/enterprise-dark.png",
    tags: ["professional", "mega", "dark", "enterprise"],
    colorPalette: {
      primary: "#e2e8f0",
      secondary: "#94a3b8",
      accent: "#22d3ee",
      text: "#94a3b8",
      bg: "#0f172a",
    },
    config: {
      layout: "MULTI_COLUMN",
      columns: 5,
      bgType: "solid",
      bgColor: "#0f172a",
      textColor: "#cbd5e1",
      headingColor: "#f1f5f9",
      linkColor: "#e2e8f0",
      linkHoverColor: "#22d3ee",
      accentColor: "#22d3ee",
      borderColor: "#475569",  // Visible input border on dark bg
      headingSize: "sm",
      headingWeight: "semibold",
      headingStyle: "uppercase",
      socialShape: "circle",
      socialSize: "lg",
      socialColorMode: "brand",
      socialHoverEffect: "scale",
      socialBgStyle: "outline",
      dividerStyle: "solid",
      dividerColor: "#22d3ee",
      linkHoverEffect: "color",
      topBorderStyle: "none",
      shadow: "none",
      paddingTop: 64,
      paddingBottom: 40,
      bottomBarLayout: "split",
      containerWidth: "full",
      containerStyle: "sharp",
      newsletterEnabled: true,
      // Animation - Professional fade-up for enterprise feel
      enableAnimations: true,
      entranceAnimation: "fade-up",
      animationDuration: 400,
      // Widgets configuration
      widgets: [
        {
          type: "BRAND",
          title: "",
          showTitle: false,
          column: 1,
          sortOrder: 0,
          content: {
            tagline: "Your Business Formation Partner",
            showContact: false,
            showSocial: false,
          },
        },
        {
          type: "NEWSLETTER",
          title: "Stay Updated",
          showTitle: true,
          column: 1,
          sortOrder: 1,
          content: {
            subtitle: "Get the latest updates and tips",
            buttonText: "Subscribe",
            style: "inline",
          },
        },
        {
          type: "SOCIAL",
          title: "Follow Us",
          showTitle: true,
          column: 1,
          sortOrder: 2,
          content: {},
        },
        {
          type: "LINKS",
          title: "Company",
          showTitle: true,
          column: 2,
          sortOrder: 0,
          menuItems: [
            { label: "About Us", url: "/about" },
            { label: "Our Team", url: "/team" },
            { label: "Careers", url: "/careers" },
            { label: "Press", url: "/press" },
          ],
        },
        {
          type: "LINKS",
          title: "Services",
          showTitle: true,
          column: 3,
          sortOrder: 0,
          menuItems: [
            { label: "LLC Formation", url: "/services/llc-formation" },
            { label: "EIN Application", url: "/services/ein-application" },
            { label: "Registered Agent", url: "/services/registered-agent" },
            { label: "Business Banking", url: "/services/business-banking" },
          ],
        },
        {
          type: "LINKS",
          title: "Resources",
          showTitle: true,
          column: 4,
          sortOrder: 0,
          menuItems: [
            { label: "Blog", url: "/blog" },
            { label: "Guides", url: "/guides" },
            { label: "State Fees", url: "/state-fees" },
            { label: "FAQs", url: "/faq" },
          ],
        },
        {
          type: "LINKS",
          title: "Support",
          showTitle: true,
          column: 5,
          sortOrder: 0,
          menuItems: [
            { label: "Contact Us", url: "/contact" },
            { label: "Help Center", url: "/help" },
            { label: "Live Chat", url: "/chat" },
            { label: "Support Tickets", url: "/dashboard/tickets" },
          ],
        },
      ],
      bottomLinks: [
        { label: "Privacy Policy", url: "/privacy" },
        { label: "Terms of Service", url: "/terms" },
        { label: "Refund Policy", url: "/refund-policy" },
        { label: "Disclaimer", url: "/disclaimer" },
      ],
    },
  },

  // ============ MODERN CATEGORY ============
  {
    name: "SaaS Modern",
    description: "Stacked layout with gradient. Newsletter on top, links below. Perfect for SaaS.",
    category: "modern",
    thumbnail: "/presets/footer/saas-modern.png",
    tags: ["modern", "gradient", "saas", "tech", "stacked"],
    colorPalette: {
      primary: "#ffffff",
      secondary: "#c7d2fe",
      accent: "#818cf8",
      text: "#e0e7ff",
      bg: "#4338ca",
    },
    config: {
      layout: "STACKED",  // Stacked layout - newsletter hero on top
      columns: 4,
      bgType: "gradient",
      bgGradient: {
        type: "linear",
        colors: [
          { color: "#4338ca", position: 0 },
          { color: "#6366f1", position: 50 },
          { color: "#818cf8", position: 100 },
        ],
        angle: 135,
      },
      textColor: "#e0e7ff",
      headingColor: "#ffffff",
      linkColor: "#c7d2fe",
      linkHoverColor: "#ffffff",
      accentColor: "#a5b4fc",
      borderColor: "#818cf8",  // Visible input border on gradient
      headingSize: "base",
      headingWeight: "bold",
      headingStyle: "normal",
      socialShape: "pill",
      socialSize: "md",
      socialColorMode: "monochrome",
      socialHoverEffect: "scale",
      socialBgStyle: "outline",
      dividerStyle: "solid",
      dividerColor: "#6366f1",
      linkHoverEffect: "color",
      topBorderStyle: "none",
      shadow: "none",
      paddingTop: 64,
      paddingBottom: 40,
      bottomBarLayout: "centered",
      containerWidth: "full",
      containerStyle: "sharp",
      enableAnimations: true,
      entranceAnimation: "fade-up",
      animationDuration: 400,
      newsletterEnabled: true,
      widgets: createStandardWidgets("Build Something Amazing"),
      bottomLinks: standardBottomLinks,
    },
  },
  {
    name: "Glassmorphism",
    description: "Trendy frosted glass effect. Boxed container with rounded corners.",
    category: "modern",
    thumbnail: "/presets/footer/glassmorphism.png",
    tags: ["modern", "glass", "blur", "trendy"],
    colorPalette: {
      primary: "#1e293b",
      secondary: "#64748b",
      accent: "#0ea5e9",
      text: "#475569",
      bg: "rgba(255,255,255,0.9)",
    },
    config: {
      layout: "MULTI_COLUMN",
      columns: 5,
      bgType: "solid",
      bgColor: "rgba(255,255,255,0.95)",
      textColor: "#475569",
      headingColor: "#1e293b",
      linkColor: "#475569",
      linkHoverColor: "#0ea5e9",
      accentColor: "#0ea5e9",
      borderColor: "#94a3b8",  // Visible input border
      headingSize: "sm",
      headingWeight: "semibold",
      headingStyle: "normal",
      socialShape: "rounded",
      socialSize: "md",
      socialColorMode: "brand",
      socialHoverEffect: "lift",
      socialBgStyle: "outline",
      dividerStyle: "solid",
      dividerColor: "#cbd5e1",
      linkHoverEffect: "color",
      topBorderStyle: "solid",
      topBorderHeight: 1,
      topBorderColor: "#e2e8f0",
      shadow: "lg",
      paddingTop: 48,
      paddingBottom: 32,
      bottomBarLayout: "split",
      containerWidth: "boxed",
      containerStyle: "round",
      cornerRadiusTL: 24,
      cornerRadiusTR: 24,
      cornerRadiusBL: 0,
      cornerRadiusBR: 0,
      enableAnimations: true,
      entranceAnimation: "fade-up",
      animationDuration: 350,
      newsletterEnabled: true,
      widgets: createStandardWidgets("Modern Design, Timeless Quality"),
      bottomLinks: standardBottomLinks,
    },
  },
  {
    name: "Neon Tech",
    description: "Mega layout with neon glow effects. Cyberpunk-inspired dark theme.",
    category: "modern",
    thumbnail: "/presets/footer/neon-tech.png",
    tags: ["modern", "neon", "dark", "cyberpunk", "mega"],
    colorPalette: {
      primary: "#f0abfc",
      secondary: "#a855f7",
      accent: "#22d3ee",
      text: "#c084fc",
      bg: "#0c0a1d",
    },
    config: {
      layout: "MEGA",  // Mega layout - large comprehensive footer
      columns: 5,
      bgType: "solid",
      bgColor: "#0c0a1d",
      textColor: "#c4b5fd",  // Brighter for readability
      headingColor: "#f0abfc",
      linkColor: "#c4b5fd",
      linkHoverColor: "#22d3ee",
      accentColor: "#22d3ee",
      borderColor: "#7c3aed",  // Visible neon input border
      headingSize: "sm",
      headingWeight: "bold",
      headingStyle: "uppercase",
      socialShape: "square",
      socialSize: "lg",
      socialColorMode: "accent",
      socialHoverEffect: "glow",
      socialBgStyle: "outline",
      dividerStyle: "gradient",
      dividerColor: "#7c3aed",
      linkHoverEffect: "color",
      topBorderStyle: "gradient",
      topBorderHeight: 3,
      topBorderColor: "#22d3ee",
      shadow: "none",
      paddingTop: 64,
      paddingBottom: 40,
      bottomBarLayout: "split",
      containerWidth: "full",
      containerStyle: "sharp",
      enableAnimations: true,
      entranceAnimation: "fade-in",
      animationDuration: 300,
      newsletterEnabled: true,
      widgets: createStandardWidgets("Future-Ready Solutions"),
      bottomLinks: standardBottomLinks,
    },
  },

  // ============ CREATIVE CATEGORY ============
  {
    name: "Colorful Dots",
    description: "Playful dots pattern (30% opacity) on warm background. Fun and creative.",
    category: "creative",
    thumbnail: "/presets/footer/colorful-blocks.png",
    tags: ["creative", "colorful", "playful", "dots", "pattern"],
    colorPalette: {
      primary: "#1e293b",
      secondary: "#64748b",
      accent: "#f472b6",
      text: "#475569",
      bg: "#fef3c7",
    },
    config: {
      layout: "CENTERED",  // Centered layout for creative feel
      columns: 4,
      bgType: "pattern",
      bgColor: "#fef3c7",
      bgPattern: "dots",
      bgPatternColor: "#d97706",  // Darker dots for visibility
      bgPatternOpacity: 30,  // 30% opacity - visible but not distracting
      textColor: "#57534e",  // Darker for readability on light bg
      headingColor: "#292524",
      linkColor: "#57534e",
      linkHoverColor: "#f472b6",
      accentColor: "#f472b6",
      borderColor: "#78716c",  // Darker border for better visibility
      headingSize: "base",
      headingWeight: "bold",
      headingStyle: "normal",
      socialShape: "circle",
      socialSize: "lg",
      socialColorMode: "brand",
      socialHoverEffect: "rotate",
      socialBgStyle: "solid",
      dividerStyle: "dashed",
      dividerColor: "#d97706",
      linkHoverEffect: "color",
      topBorderStyle: "none",
      shadow: "none",
      paddingTop: 56,
      paddingBottom: 40,
      bottomBarLayout: "centered",
      containerWidth: "full",
      containerStyle: "sharp",
      enableAnimations: true,
      entranceAnimation: "fade-up",
      animationDuration: 400,
      newsletterEnabled: true,
      widgets: createStandardWidgets("Creative Solutions for Your Business"),
      bottomLinks: standardBottomLinks,
    },
  },

  // ============ INDUSTRY CATEGORY ============
  {
    name: "E-commerce Pro",
    description: "MEGA layout with trust badges section. Comprehensive for e-commerce sites.",
    category: "industry",
    thumbnail: "/presets/footer/ecommerce-pro.png",
    tags: ["industry", "ecommerce", "trust", "mega"],
    colorPalette: {
      primary: "#059669",
      secondary: "#6b7280",
      accent: "#10b981",
      text: "#4b5563",
      bg: "#f9fafb",
    },
    config: {
      layout: "MEGA",  // Mega layout for comprehensive footer
      columns: 5,
      bgType: "solid",
      bgColor: "#f9fafb",
      textColor: "#4b5563",
      headingColor: "#111827",
      linkColor: "#4b5563",
      linkHoverColor: "#059669",
      accentColor: "#10b981",
      borderColor: "#9ca3af",  // Visible input border
      headingSize: "sm",
      headingWeight: "semibold",
      headingStyle: "normal",
      socialShape: "rounded",
      socialSize: "md",
      socialColorMode: "brand",
      socialHoverEffect: "scale",
      socialBgStyle: "subtle",
      dividerStyle: "solid",
      dividerColor: "#d1d5db",
      linkHoverEffect: "color",
      topBorderStyle: "solid",
      topBorderHeight: 4,
      topBorderColor: "#059669",
      shadow: "sm",
      paddingTop: 64,
      paddingBottom: 48,
      bottomBarLayout: "stacked",
      containerWidth: "full",
      containerStyle: "sharp",
      showTrustBadges: true,
      enableAnimations: true,
      entranceAnimation: "fade-up",
      animationDuration: 300,
      newsletterEnabled: true,
      widgets: createStandardWidgets("Shop With Confidence"),
      bottomLinks: standardBottomLinks,
    },
  },
  {
    name: "Legal Services",
    description: "Professional multi-column layout. Trustworthy design for law firms.",
    category: "industry",
    thumbnail: "/presets/footer/legal-services.png",
    tags: ["industry", "legal", "professional", "trust"],
    colorPalette: {
      primary: "#1e3a5f",
      secondary: "#64748b",
      accent: "#0369a1",
      text: "#475569",
      bg: "#ffffff",
    },
    config: {
      layout: "MULTI_COLUMN",
      columns: 5,
      bgType: "solid",
      bgColor: "#ffffff",
      textColor: "#475569",
      headingColor: "#1e3a5f",
      linkColor: "#475569",
      linkHoverColor: "#0369a1",
      accentColor: "#0369a1",
      borderColor: "#94a3b8",  // Visible input border on white
      headingSize: "sm",
      headingWeight: "semibold",
      headingStyle: "normal",
      socialShape: "square",
      socialSize: "sm",
      socialColorMode: "monochrome",
      socialHoverEffect: "lift",
      socialBgStyle: "outline",
      dividerStyle: "solid",
      dividerColor: "#e2e8f0",
      linkHoverEffect: "color",
      topBorderStyle: "solid",
      topBorderHeight: 4,
      topBorderColor: "#1e3a5f",
      shadow: "none",
      paddingTop: 56,
      paddingBottom: 40,
      bottomBarLayout: "split",
      containerWidth: "full",
      containerStyle: "sharp",
      enableAnimations: true,
      entranceAnimation: "fade-up",
      animationDuration: 300,
      newsletterEnabled: true,
      widgets: createStandardWidgets("Trusted Legal Solutions"),
      bottomLinks: standardBottomLinks,
    },
  },
  {
    name: "App Launch",
    description: "STACKED layout with gradient. App download focused with prominent CTA.",
    category: "industry",
    thumbnail: "/presets/footer/app-launch.png",
    tags: ["industry", "app", "mobile", "stacked"],
    colorPalette: {
      primary: "#7c3aed",
      secondary: "#a78bfa",
      accent: "#8b5cf6",
      text: "#c4b5fd",
      bg: "#1e1b4b",
    },
    config: {
      layout: "STACKED",  // Stacked layout - app download hero on top
      columns: 4,
      bgType: "gradient",
      bgGradient: {
        type: "linear",
        colors: [
          { color: "#1e1b4b", position: 0 },
          { color: "#312e81", position: 100 },
        ],
        angle: 180,
      },
      textColor: "#ddd6fe",  // Brighter for readability
      headingColor: "#ffffff",
      linkColor: "#c4b5fd",
      linkHoverColor: "#f5f3ff",
      accentColor: "#a78bfa",
      borderColor: "#7c3aed",  // Visible input border
      headingSize: "sm",
      headingWeight: "bold",
      headingStyle: "uppercase",
      socialShape: "circle",
      socialSize: "lg",
      socialColorMode: "accent",
      socialHoverEffect: "scale",
      socialBgStyle: "outline",
      dividerStyle: "solid",
      dividerColor: "#4c1d95",
      linkHoverEffect: "color",
      topBorderStyle: "none",
      shadow: "none",
      paddingTop: 72,
      paddingBottom: 48,
      bottomBarLayout: "centered",
      containerWidth: "full",
      containerStyle: "sharp",
      enableAnimations: true,
      entranceAnimation: "slide-up",
      animationDuration: 400,
      newsletterEnabled: true,
      widgets: createStandardWidgets("Download Our App Today"),
      bottomLinks: standardBottomLinks,
    },
  },
  {
    name: "Newsletter First",
    description: "STACKED layout with newsletter hero. Marketing focused with prominent signup.",
    category: "industry",
    thumbnail: "/presets/footer/newsletter-first.png",
    tags: ["industry", "newsletter", "marketing", "stacked"],
    colorPalette: {
      primary: "#dc2626",
      secondary: "#6b7280",
      accent: "#ef4444",
      text: "#4b5563",
      bg: "#fef2f2",
    },
    config: {
      layout: "STACKED",  // Stacked layout - newsletter hero on top
      columns: 4,
      bgType: "solid",
      bgColor: "#fef2f2",
      textColor: "#4b5563",
      headingColor: "#1f2937",
      linkColor: "#4b5563",
      linkHoverColor: "#dc2626",
      accentColor: "#dc2626",
      borderColor: "#f87171",  // Red-tinted border for theme
      headingSize: "sm",
      headingWeight: "semibold",
      headingStyle: "normal",
      socialShape: "circle",
      socialSize: "md",
      socialColorMode: "brand",
      socialHoverEffect: "scale",
      socialBgStyle: "subtle",
      dividerStyle: "solid",
      dividerColor: "#fecaca",
      linkHoverEffect: "color",
      topBorderStyle: "none",
      shadow: "none",
      paddingTop: 64,
      paddingBottom: 48,
      bottomBarLayout: "split",
      containerWidth: "full",
      containerStyle: "sharp",
      newsletterEnabled: true,
      newsletterTitle: "Stay in the loop",
      newsletterSubtitle: "Get the latest updates and exclusive offers.",
      enableAnimations: true,
      entranceAnimation: "fade-up",
      animationDuration: 350,
      widgets: createStandardWidgets("Join Our Community"),
      bottomLinks: standardBottomLinks,
    },
  },

  // ============ NEW PREMIUM PRESETS ============
  {
    name: "Ocean Gradient",
    description: "Ocean blue to teal gradient. STACKED layout for immersive brand experience.",
    category: "modern",
    thumbnail: "/presets/footer/ocean-gradient.png",
    tags: ["modern", "gradient", "ocean", "blue", "stacked"],
    colorPalette: {
      primary: "#ffffff",
      secondary: "#a5f3fc",
      accent: "#06b6d4",
      text: "#cffafe",
      bg: "#0c4a6e",
    },
    config: {
      layout: "STACKED",  // Stacked layout for immersive feel
      columns: 4,
      bgType: "gradient",
      bgGradient: {
        type: "linear",
        colors: [
          { color: "#0c4a6e", position: 0 },
          { color: "#0e7490", position: 50 },
          { color: "#06b6d4", position: 100 },
        ],
        angle: 135,
      },
      textColor: "#cffafe",
      headingColor: "#ffffff",
      linkColor: "#a5f3fc",
      linkHoverColor: "#ffffff",
      accentColor: "#22d3ee",
      borderColor: "#0891b2",  // Visible input border
      headingSize: "sm",
      headingWeight: "semibold",
      headingStyle: "uppercase",
      socialShape: "circle",
      socialSize: "md",
      socialColorMode: "monochrome",
      socialHoverEffect: "lift",
      socialBgStyle: "outline",
      dividerStyle: "solid",
      dividerColor: "#0891b2",
      linkHoverEffect: "color",
      topBorderStyle: "none",
      shadow: "none",
      paddingTop: 64,
      paddingBottom: 40,
      bottomBarLayout: "centered",
      containerWidth: "full",
      containerStyle: "sharp",
      enableAnimations: true,
      entranceAnimation: "fade-up",
      animationDuration: 400,
      newsletterEnabled: true,
      widgets: createStandardWidgets("Dive Into Success"),
      bottomLinks: standardBottomLinks,
    },
  },
  {
    name: "Emerald Professional",
    description: "Deep emerald green solid background. MEGA layout for enterprise.",
    category: "professional",
    thumbnail: "/presets/footer/emerald-professional.png",
    tags: ["professional", "green", "emerald", "mega"],
    colorPalette: {
      primary: "#ffffff",
      secondary: "#a7f3d0",
      accent: "#10b981",
      text: "#d1fae5",
      bg: "#064e3b",
    },
    config: {
      layout: "MEGA",  // Mega layout for comprehensive coverage
      columns: 5,
      bgType: "solid",
      bgColor: "#064e3b",
      textColor: "#d1fae5",
      headingColor: "#ffffff",
      linkColor: "#a7f3d0",
      linkHoverColor: "#34d399",
      accentColor: "#10b981",
      borderColor: "#059669",  // Visible input border
      headingSize: "sm",
      headingWeight: "semibold",
      headingStyle: "normal",
      socialShape: "rounded",
      socialSize: "md",
      socialColorMode: "brand",
      socialHoverEffect: "scale",
      socialBgStyle: "outline",
      dividerStyle: "solid",
      dividerColor: "#059669",
      linkHoverEffect: "color",
      topBorderStyle: "solid",
      topBorderHeight: 3,
      topBorderColor: "#10b981",
      shadow: "none",
      paddingTop: 64,
      paddingBottom: 40,
      bottomBarLayout: "split",
      containerWidth: "full",
      containerStyle: "sharp",
      enableAnimations: true,
      entranceAnimation: "fade-up",
      animationDuration: 350,
      newsletterEnabled: true,
      widgets: createStandardWidgets("Growing Your Business"),
      bottomLinks: standardBottomLinks,
    },
  },
  {
    name: "Midnight Purple",
    description: "Deep purple gradient. MINIMAL layout with neon accents.",
    category: "modern",
    thumbnail: "/presets/footer/midnight-purple.png",
    tags: ["modern", "purple", "dark", "minimal"],
    colorPalette: {
      primary: "#e9d5ff",
      secondary: "#c4b5fd",
      accent: "#a855f7",
      text: "#d8b4fe",
      bg: "#1e1033",
    },
    config: {
      layout: "MINIMAL",  // Minimal layout for clean look
      columns: 4,
      bgType: "gradient",
      bgGradient: {
        type: "linear",
        colors: [
          { color: "#1e1033", position: 0 },
          { color: "#2e1065", position: 100 },
        ],
        angle: 180,
      },
      textColor: "#e9d5ff",  // Brighter for readability
      headingColor: "#f3e8ff",
      linkColor: "#d8b4fe",
      linkHoverColor: "#a855f7",
      accentColor: "#a855f7",
      borderColor: "#7c3aed",  // Visible input border
      headingSize: "sm",
      headingWeight: "semibold",
      headingStyle: "uppercase",
      socialShape: "pill",
      socialSize: "md",
      socialColorMode: "accent",
      socialHoverEffect: "glow",
      socialBgStyle: "outline",
      dividerStyle: "gradient",
      dividerColor: "#7c3aed",
      linkHoverEffect: "color",
      topBorderStyle: "gradient",
      topBorderHeight: 2,
      topBorderColor: "#a855f7",
      shadow: "none",
      paddingTop: 32,
      paddingBottom: 24,
      bottomBarLayout: "split",
      containerWidth: "full",
      containerStyle: "sharp",
      enableAnimations: true,
      entranceAnimation: "fade-in",
      animationDuration: 400,
      newsletterEnabled: true,
      widgets: createStandardWidgets("Innovate Beyond Limits"),
      bottomLinks: standardBottomLinks,
    },
  },
  {
    name: "Warm Sunset",
    description: "Orange gradient with warm tones. CENTERED layout for creative brands.",
    category: "creative",
    thumbnail: "/presets/footer/warm-sunset.png",
    tags: ["creative", "gradient", "warm", "centered"],
    colorPalette: {
      primary: "#ffffff",
      secondary: "#fecaca",
      accent: "#f97316",
      text: "#fed7aa",
      bg: "#7c2d12",
    },
    config: {
      layout: "CENTERED",  // Centered layout for creative focus
      columns: 4,
      bgType: "gradient",
      bgGradient: {
        type: "linear",
        colors: [
          { color: "#7c2d12", position: 0 },
          { color: "#c2410c", position: 50 },
          { color: "#ea580c", position: 100 },
        ],
        angle: 135,
      },
      textColor: "#ffedd5",  // Brighter for readability
      headingColor: "#ffffff",
      linkColor: "#fed7aa",
      linkHoverColor: "#ffffff",
      accentColor: "#fb923c",
      borderColor: "#ea580c",  // Visible input border
      headingSize: "base",
      headingWeight: "bold",
      headingStyle: "normal",
      socialShape: "circle",
      socialSize: "lg",
      socialColorMode: "monochrome",
      socialHoverEffect: "lift",
      socialBgStyle: "solid",
      dividerStyle: "solid",
      dividerColor: "#ea580c",
      linkHoverEffect: "color",
      topBorderStyle: "none",
      shadow: "none",
      paddingTop: 56,
      paddingBottom: 40,
      bottomBarLayout: "centered",
      containerWidth: "full",
      containerStyle: "sharp",
      enableAnimations: true,
      entranceAnimation: "fade-up",
      animationDuration: 400,
      newsletterEnabled: true,
      widgets: createStandardWidgets("Ignite Your Vision"),
      bottomLinks: standardBottomLinks,
    },
  },
  {
    name: "Nordic Light",
    description: "Clean minimal on soft gray. MINIMAL layout for Scandinavian design.",
    category: "minimal",
    thumbnail: "/presets/footer/nordic-light.png",
    tags: ["minimal", "light", "nordic", "clean"],
    colorPalette: {
      primary: "#1f2937",
      secondary: "#6b7280",
      accent: "#3b82f6",
      text: "#4b5563",
      bg: "#f9fafb",
    },
    config: {
      layout: "MINIMAL",  // Minimal layout for clean Scandinavian feel
      columns: 4,
      bgType: "solid",
      bgColor: "#f9fafb",
      textColor: "#4b5563",
      headingColor: "#1f2937",
      linkColor: "#4b5563",
      linkHoverColor: "#3b82f6",
      accentColor: "#3b82f6",
      borderColor: "#9ca3af",  // Visible input border on light bg
      headingSize: "sm",
      headingWeight: "medium",
      headingStyle: "normal",
      socialShape: "circle",
      socialSize: "sm",
      socialColorMode: "monochrome",
      socialHoverEffect: "scale",
      socialBgStyle: "outline",
      dividerStyle: "solid",
      dividerColor: "#e5e7eb",
      linkHoverEffect: "color",
      topBorderStyle: "none",
      shadow: "none",
      paddingTop: 32,
      paddingBottom: 24,
      bottomBarLayout: "split",
      containerWidth: "full",
      containerStyle: "sharp",
      enableAnimations: true,
      entranceAnimation: "fade-up",
      animationDuration: 250,
      newsletterEnabled: true,
      widgets: createStandardWidgets("Simplicity Meets Excellence"),
      bottomLinks: standardBottomLinks,
    },
  },
  {
    name: "Carbon Fiber",
    description: "Diagonal pattern (40% opacity) on dark. Tech-inspired industrial design.",
    category: "modern",
    thumbnail: "/presets/footer/carbon-fiber.png",
    tags: ["modern", "dark", "pattern", "tech", "diagonal"],
    colorPalette: {
      primary: "#e5e5e5",
      secondary: "#a3a3a3",
      accent: "#ef4444",
      text: "#d4d4d4",
      bg: "#171717",
    },
    config: {
      layout: "MULTI_COLUMN",
      columns: 5,
      bgType: "pattern",
      bgColor: "#171717",
      bgPattern: "diagonal",
      bgPatternColor: "#404040",  // Brighter for visibility
      bgPatternOpacity: 40,  // 40% opacity for clear visibility
      textColor: "#e5e5e5",  // Brighter for readability
      headingColor: "#f5f5f5",
      linkColor: "#d4d4d4",
      linkHoverColor: "#ef4444",
      accentColor: "#ef4444",
      borderColor: "#525252",  // Visible input border on dark
      headingSize: "sm",
      headingWeight: "bold",
      headingStyle: "uppercase",
      socialShape: "square",
      socialSize: "md",
      socialColorMode: "accent",
      socialHoverEffect: "scale",
      socialBgStyle: "outline",
      dividerStyle: "solid",
      dividerColor: "#404040",
      linkHoverEffect: "color",
      topBorderStyle: "solid",
      topBorderHeight: 2,
      topBorderColor: "#ef4444",
      shadow: "none",
      paddingTop: 64,
      paddingBottom: 40,
      bottomBarLayout: "split",
      containerWidth: "full",
      containerStyle: "sharp",
      enableAnimations: true,
      entranceAnimation: "fade-in",
      animationDuration: 300,
      newsletterEnabled: true,
      widgets: createStandardWidgets("Engineered for Performance"),
      bottomLinks: standardBottomLinks,
    },
  },
  {
    name: "Rose Gold",
    description: "Elegant rose gold theme for luxury and fashion brands.",
    category: "creative",
    thumbnail: "/presets/footer/rose-gold.png",
    tags: ["creative", "elegant", "rose", "luxury"],
    colorPalette: {
      primary: "#1f2937",
      secondary: "#9ca3af",
      accent: "#f472b6",
      text: "#6b7280",
      bg: "#fdf2f8",
    },
    config: {
      layout: "MULTI_COLUMN",
      columns: 5,
      bgType: "solid",
      bgColor: "#fdf2f8",
      textColor: "#57534e",  // Darker stone for better readability
      headingColor: "#831843",
      linkColor: "#78716c",  // Warmer gray for links
      linkHoverColor: "#ec4899",
      accentColor: "#ec4899",
      borderColor: "#be185d",  // Darker rose for visible border
      headingSize: "sm",
      headingWeight: "medium",
      headingStyle: "normal",
      socialShape: "circle",
      socialSize: "md",
      socialColorMode: "accent",
      socialHoverEffect: "lift",
      socialBgStyle: "subtle",
      dividerStyle: "solid",
      dividerColor: "#fbcfe8",
      linkHoverEffect: "color",
      topBorderStyle: "solid",
      topBorderHeight: 1,
      topBorderColor: "#f9a8d4",
      shadow: "sm",
      paddingTop: 56,
      paddingBottom: 40,
      bottomBarLayout: "centered",
      containerWidth: "full",
      containerStyle: "sharp",
      enableAnimations: true,
      entranceAnimation: "fade-up",
      animationDuration: 350,
      newsletterEnabled: true,
      widgets: createStandardWidgets("Elegance Redefined"),
      bottomLinks: standardBottomLinks,
    },
  },
  {
    name: "Forest Deep",
    description: "Nature-inspired deep green theme for eco-friendly businesses.",
    category: "industry",
    thumbnail: "/presets/footer/forest-deep.png",
    tags: ["industry", "nature", "green", "eco"],
    colorPalette: {
      primary: "#d1fae5",
      secondary: "#a7f3d0",
      accent: "#22c55e",
      text: "#bbf7d0",
      bg: "#14532d",
    },
    config: {
      layout: "MULTI_COLUMN",
      columns: 5,
      bgType: "gradient",
      bgGradient: {
        type: "linear",
        colors: [
          { color: "#14532d", position: 0 },
          { color: "#166534", position: 100 },
        ],
        angle: 180,
      },
      textColor: "#bbf7d0",
      headingColor: "#dcfce7",
      linkColor: "#a7f3d0",
      linkHoverColor: "#4ade80",
      accentColor: "#22c55e",
      borderColor: "#16a34a",  // Forest green input border
      headingSize: "sm",
      headingWeight: "semibold",
      headingStyle: "normal",
      socialShape: "rounded",
      socialSize: "md",
      socialColorMode: "brand",
      socialHoverEffect: "scale",
      socialBgStyle: "subtle",
      dividerStyle: "solid",
      dividerColor: "#16a34a",
      linkHoverEffect: "color",
      topBorderStyle: "solid",
      topBorderHeight: 3,
      topBorderColor: "#22c55e",
      shadow: "none",
      paddingTop: 64,
      paddingBottom: 40,
      bottomBarLayout: "split",
      containerWidth: "full",
      containerStyle: "sharp",
      enableAnimations: true,
      entranceAnimation: "fade-up",
      animationDuration: 400,
      newsletterEnabled: true,
      widgets: createStandardWidgets("Sustainable Solutions"),
      bottomLinks: standardBottomLinks,
    },
  },
  {
    name: "Grid Pattern Dark",
    description: "Grid pattern (50% opacity) on slate. Developer-focused technical design.",
    category: "modern",
    thumbnail: "/presets/footer/grid-pattern-dark.png",
    tags: ["modern", "dark", "grid", "developer", "pattern"],
    colorPalette: {
      primary: "#a5f3fc",
      secondary: "#67e8f9",
      accent: "#06b6d4",
      text: "#94a3b8",
      bg: "#0f172a",
    },
    config: {
      layout: "MULTI_COLUMN",
      columns: 5,
      bgType: "pattern",
      bgColor: "#0f172a",
      bgPattern: "grid",
      bgPatternColor: "#334155",  // More visible grid
      bgPatternOpacity: 50,  // 50% opacity for clear visibility
      textColor: "#cbd5e1",  // Brighter for readability
      headingColor: "#f1f5f9",
      linkColor: "#cbd5e1",
      linkHoverColor: "#22d3ee",
      accentColor: "#06b6d4",
      borderColor: "#475569",  // Visible input border
      headingSize: "sm",
      headingWeight: "semibold",
      headingStyle: "uppercase",
      socialShape: "rounded",
      socialSize: "md",
      socialColorMode: "accent",
      socialHoverEffect: "glow",
      socialBgStyle: "outline",
      dividerStyle: "solid",
      dividerColor: "#334155",
      linkHoverEffect: "color",
      topBorderStyle: "gradient",
      topBorderHeight: 2,
      topBorderColor: "#06b6d4",
      shadow: "none",
      paddingTop: 64,
      paddingBottom: 40,
      bottomBarLayout: "split",
      containerWidth: "full",
      containerStyle: "sharp",
      enableAnimations: true,
      entranceAnimation: "fade-up",
      animationDuration: 350,
      newsletterEnabled: true,
      widgets: createStandardWidgets("Code Your Success"),
      bottomLinks: standardBottomLinks,
    },
  },
  {
    name: "Noise Texture",
    description: "Noise pattern (35% opacity) on dark blue. Modern textured background effect.",
    category: "modern",
    thumbnail: "/presets/footer/noise-texture.png",
    tags: ["modern", "dark", "noise", "texture", "pattern"],
    colorPalette: {
      primary: "#e0f2fe",
      secondary: "#7dd3fc",
      accent: "#0ea5e9",
      text: "#bae6fd",
      bg: "#0c4a6e",
    },
    config: {
      layout: "MULTI_COLUMN",
      columns: 5,
      bgType: "pattern",
      bgColor: "#0c4a6e",
      bgPattern: "noise",
      bgPatternColor: "#075985",
      bgPatternOpacity: 35,  // 35% opacity for visible texture
      textColor: "#bae6fd",
      headingColor: "#f0f9ff",
      linkColor: "#7dd3fc",
      linkHoverColor: "#38bdf8",
      accentColor: "#0ea5e9",
      borderColor: "#0284c7",  // Visible input border
      headingSize: "sm",
      headingWeight: "semibold",
      headingStyle: "normal",
      socialShape: "circle",
      socialSize: "md",
      socialColorMode: "monochrome",
      socialHoverEffect: "scale",
      socialBgStyle: "subtle",
      dividerStyle: "solid",
      dividerColor: "#0369a1",
      linkHoverEffect: "color",
      topBorderStyle: "none",
      shadow: "none",
      paddingTop: 64,
      paddingBottom: 40,
      bottomBarLayout: "split",
      containerWidth: "full",
      containerStyle: "sharp",
      enableAnimations: true,
      entranceAnimation: "fade-up",
      animationDuration: 400,
      newsletterEnabled: true,
      widgets: createStandardWidgets("Quality You Can Trust"),
      bottomLinks: standardBottomLinks,
    },
  },
  {
    name: "Waves Pattern",
    description: "Waves pattern (25% opacity) on teal. Organic flowing design for creative brands.",
    category: "creative",
    thumbnail: "/presets/footer/waves-pattern.png",
    tags: ["creative", "pattern", "waves", "organic"],
    colorPalette: {
      primary: "#99f6e4",
      secondary: "#5eead4",
      accent: "#14b8a6",
      text: "#ccfbf1",
      bg: "#134e4a",
    },
    config: {
      layout: "CENTERED",  // Centered layout for organic feel
      columns: 4,
      bgType: "pattern",
      bgColor: "#134e4a",
      bgPattern: "waves",
      bgPatternColor: "#115e59",
      bgPatternOpacity: 25,  // 25% opacity - subtle waves
      textColor: "#ccfbf1",
      headingColor: "#f0fdfa",
      linkColor: "#99f6e4",
      linkHoverColor: "#2dd4bf",
      accentColor: "#14b8a6",
      borderColor: "#0d9488",  // Visible input border
      headingSize: "sm",
      headingWeight: "medium",
      headingStyle: "normal",
      socialShape: "pill",
      socialSize: "md",
      socialColorMode: "monochrome",
      socialHoverEffect: "lift",
      socialBgStyle: "outline",
      dividerStyle: "solid",
      dividerColor: "#0f766e",
      linkHoverEffect: "color",
      topBorderStyle: "wave",
      topBorderHeight: 6,
      topBorderColor: "#2dd4bf",
      shadow: "none",
      paddingTop: 56,
      paddingBottom: 40,
      bottomBarLayout: "centered",
      containerWidth: "full",
      containerStyle: "sharp",
      enableAnimations: true,
      entranceAnimation: "fade-up",
      animationDuration: 450,
      newsletterEnabled: true,
      widgets: createStandardWidgets("Flow With Us"),
      bottomLinks: standardBottomLinks,
    },
  },
];

export async function seedFooterPresets() {
  console.log("🎨 Seeding footer presets...");

  for (const preset of footerPresets) {
    const existing = await prisma.footerPreset.findFirst({
      where: { name: preset.name, isBuiltIn: true },
    });

    if (existing) {
      // Update existing preset
      await prisma.footerPreset.update({
        where: { id: existing.id },
        data: {
          ...preset,
          isBuiltIn: true,
          isPublic: true,
        },
      });
      console.log(`  ✓ Updated preset: ${preset.name}`);
    } else {
      // Create new preset
      await prisma.footerPreset.create({
        data: {
          ...preset,
          isBuiltIn: true,
          isPublic: true,
        },
      });
      console.log(`  ✓ Created preset: ${preset.name}`);
    }
  }

  console.log(`✅ Seeded ${footerPresets.length} footer presets`);
}

// Run if executed directly
seedFooterPresets()
  .then(async () => {
    console.log("🎉 Footer presets seeding complete!");
    await prisma.$disconnect();
    await pool.end();
    process.exit(0);
  })
  .catch(async (e) => {
    console.error(e);
    await prisma.$disconnect();
    await pool.end();
    process.exit(1);
  });
