import { NextResponse } from "next/server";
import prisma from "@/lib/db";
import { checkAdminOnly, authError } from "@/lib/admin-auth";

// Example links for widgets
const companyLinks = [
  { label: "About Us", url: "/about", target: "_self" },
  { label: "Our Team", url: "/team", target: "_self" },
  { label: "Careers", url: "/careers", target: "_self" },
  { label: "Press", url: "/press", target: "_self" },
];

const servicesLinks = [
  { label: "LLC Formation", url: "/services/llc-formation", target: "_self" },
  { label: "EIN Application", url: "/services/ein", target: "_self" },
  { label: "Registered Agent", url: "/services/registered-agent", target: "_self" },
  { label: "Business Banking", url: "/services/business-banking", target: "_self" },
];

const resourcesLinks = [
  { label: "Blog", url: "/blog", target: "_self" },
  { label: "Guides", url: "/guides", target: "_self" },
  { label: "State Fees", url: "/state-fees", target: "_self" },
  { label: "FAQs", url: "/faq", target: "_self" },
];

const supportLinks = [
  { label: "Contact Us", url: "/contact", target: "_self" },
  { label: "Help Center", url: "/help", target: "_self" },
  { label: "Live Chat", url: "#chat", target: "_self" },
  { label: "Support Tickets", url: "/support", target: "_self" },
];

const legalLinks = [
  { label: "Privacy Policy", url: "/privacy", target: "_self" },
  { label: "Terms of Service", url: "/terms", target: "_self" },
  { label: "Refund Policy", url: "/refund-policy", target: "_self" },
  { label: "Disclaimer", url: "/disclaimer", target: "_self" },
];

// 12 Built-in Footer Presets with Widgets
const footerPresets = [
  // ============ MINIMAL CATEGORY ============
  {
    name: "Clean Minimal",
    description: "Simple, clean footer with centered logo and inline links. Perfect for modern landing pages.",
    category: "minimal",
    thumbnail: "/presets/footer/clean-minimal.png",
    tags: ["minimal", "centered", "clean", "light"],
    colorPalette: {
      primary: "#000000",
      secondary: "#6b7280",
      accent: "#2563eb",
      text: "#374151",
      bg: "#ffffff",
    },
    config: {
      layout: "CENTERED",
      columns: 4,
      bgType: "solid",
      bgColor: "#ffffff",
      textColor: "#6b7280",
      headingColor: "#111827",
      linkColor: "#374151",
      linkHoverColor: "#2563eb",
      headingSize: "sm",
      headingWeight: "semibold",
      socialShape: "circle",
      socialSize: "md",
      socialColorMode: "monochrome",
      socialHoverEffect: "scale",
      dividerStyle: "none",
      topBorderStyle: "none",
      shadow: "none",
      paddingTop: 48,
      paddingBottom: 32,
      bottomBarEnabled: true,
      bottomBarLayout: "centered",
      showSocialLinks: true,
      showDisclaimer: true,
      disclaimerText: "LLCPad is not a law firm and does not provide legal advice.",
      copyrightText: `© ${new Date().getFullYear()} LLCPad. All rights reserved.`,
      bottomLinks: legalLinks.slice(0, 3),
      widgets: [
        { type: "BRAND", title: "", showTitle: false, column: 1, sortOrder: 0, content: { showTagline: true, tagline: "Your trusted LLC formation partner" } },
        { type: "SOCIAL", title: "", showTitle: false, column: 1, sortOrder: 1, content: {} },
      ],
    },
  },
  {
    name: "Dark Elegance",
    description: "Sophisticated dark footer with subtle accents. Great for premium brands.",
    category: "minimal",
    thumbnail: "/presets/footer/dark-elegance.png",
    tags: ["minimal", "dark", "elegant", "premium"],
    colorPalette: {
      primary: "#ffffff",
      secondary: "#9ca3af",
      accent: "#f59e0b",
      text: "#9ca3af",
      bg: "#111827",
    },
    config: {
      layout: "MINIMAL",
      columns: 4,
      bgType: "solid",
      bgColor: "#111827",
      textColor: "#9ca3af",
      headingColor: "#ffffff",
      linkColor: "#d1d5db",
      linkHoverColor: "#f59e0b",
      headingSize: "sm",
      headingWeight: "medium",
      headingStyle: "uppercase",
      socialShape: "rounded",
      socialSize: "md",
      socialColorMode: "monochrome",
      socialHoverEffect: "glow",
      topBorderStyle: "gradient",
      topBorderHeight: 2,
      topBorderColor: "#f59e0b",
      shadow: "none",
      paddingTop: 32,
      paddingBottom: 24,
      bottomBarEnabled: true,
      bottomBarLayout: "split",
      showSocialLinks: true,
      showDisclaimer: false,
      copyrightText: `© ${new Date().getFullYear()} LLCPad. All rights reserved.`,
      bottomLinks: legalLinks.slice(0, 2),
      widgets: [
        { type: "BRAND", title: "", showTitle: false, column: 1, sortOrder: 0, content: {} },
        { type: "SOCIAL", title: "", showTitle: false, column: 1, sortOrder: 1, content: {} },
      ],
    },
  },

  // ============ PROFESSIONAL CATEGORY ============
  {
    name: "Corporate Standard",
    description: "Classic multi-column layout for professional businesses. Clean and organized.",
    category: "professional",
    thumbnail: "/presets/footer/corporate-standard.png",
    tags: ["professional", "multi-column", "corporate", "light"],
    colorPalette: {
      primary: "#1e40af",
      secondary: "#64748b",
      accent: "#3b82f6",
      text: "#475569",
      bg: "#f8fafc",
    },
    config: {
      layout: "MULTI_COLUMN",
      columns: 4,
      bgType: "solid",
      bgColor: "#f8fafc",
      textColor: "#64748b",
      headingColor: "#1e293b",
      linkColor: "#475569",
      linkHoverColor: "#3b82f6",
      headingSize: "sm",
      headingWeight: "semibold",
      socialShape: "square",
      socialSize: "md",
      socialColorMode: "brand",
      socialHoverEffect: "lift",
      topBorderStyle: "solid",
      topBorderHeight: 1,
      topBorderColor: "#e2e8f0",
      dividerStyle: "solid",
      dividerColor: "#e2e8f0",
      shadow: "none",
      paddingTop: 64,
      paddingBottom: 40,
      bottomBarEnabled: true,
      bottomBarLayout: "split",
      showSocialLinks: true,
      showDisclaimer: true,
      disclaimerText: "LLCPad is not a law firm and does not provide legal advice.",
      copyrightText: `© ${new Date().getFullYear()} LLCPad. All rights reserved.`,
      bottomLinks: legalLinks,
      widgets: [
        { type: "BRAND", title: "", showTitle: false, column: 1, sortOrder: 0, content: { showTagline: true, tagline: "Professional LLC formation services for entrepreneurs worldwide." } },
        { type: "SOCIAL", title: "Follow Us", showTitle: true, column: 1, sortOrder: 1, content: {} },
        { type: "LINKS", title: "Company", showTitle: true, column: 2, sortOrder: 0, content: {}, menuItems: companyLinks },
        { type: "LINKS", title: "Services", showTitle: true, column: 3, sortOrder: 0, content: {}, menuItems: servicesLinks },
        { type: "LINKS", title: "Resources", showTitle: true, column: 4, sortOrder: 0, content: {}, menuItems: resourcesLinks },
      ],
    },
  },
  {
    name: "Enterprise Dark",
    description: "Full mega-footer style for large enterprise websites. Comprehensive sitemap.",
    category: "professional",
    thumbnail: "/presets/footer/enterprise-dark.png",
    tags: ["professional", "mega", "dark", "enterprise"],
    colorPalette: {
      primary: "#e2e8f0",
      secondary: "#94a3b8",
      accent: "#22d3ee",
      text: "#94a3b8",
      bg: "#0f172a",
    },
    config: {
      layout: "MEGA",
      columns: 5,
      bgType: "solid",
      bgColor: "#0f172a",
      textColor: "#94a3b8",
      headingColor: "#e2e8f0",
      linkColor: "#cbd5e1",
      linkHoverColor: "#22d3ee",
      headingSize: "sm",
      headingWeight: "semibold",
      headingStyle: "uppercase",
      socialShape: "circle",
      socialSize: "lg",
      socialColorMode: "brand",
      socialHoverEffect: "scale",
      topBorderStyle: "none",
      dividerStyle: "solid",
      dividerColor: "#1e293b",
      shadow: "none",
      paddingTop: 80,
      paddingBottom: 48,
      bottomBarEnabled: true,
      bottomBarLayout: "split",
      showSocialLinks: true,
      showDisclaimer: true,
      disclaimerText: "LLCPad is not a law firm and does not provide legal advice.",
      copyrightText: `© ${new Date().getFullYear()} LLCPad. All rights reserved.`,
      bottomLinks: legalLinks,
      widgets: [
        { type: "BRAND", title: "", showTitle: false, column: 1, sortOrder: 0, content: { showTagline: true, tagline: "Enterprise-grade LLC formation services." } },
        { type: "NEWSLETTER", title: "Stay Updated", showTitle: true, column: 1, sortOrder: 1, content: { style: "stacked" } },
        { type: "LINKS", title: "Company", showTitle: true, column: 2, sortOrder: 0, content: {}, menuItems: companyLinks },
        { type: "LINKS", title: "Services", showTitle: true, column: 3, sortOrder: 0, content: {}, menuItems: servicesLinks },
        { type: "LINKS", title: "Resources", showTitle: true, column: 4, sortOrder: 0, content: {}, menuItems: resourcesLinks },
        { type: "LINKS", title: "Support", showTitle: true, column: 5, sortOrder: 0, content: {}, menuItems: supportLinks },
      ],
    },
  },

  // ============ MODERN CATEGORY ============
  {
    name: "SaaS Modern",
    description: "Modern gradient footer perfect for SaaS and tech startups.",
    category: "modern",
    thumbnail: "/presets/footer/saas-modern.png",
    tags: ["modern", "gradient", "saas", "tech"],
    colorPalette: {
      primary: "#ffffff",
      secondary: "#c7d2fe",
      accent: "#818cf8",
      text: "#e0e7ff",
      bg: "#4338ca",
    },
    config: {
      layout: "STACKED",
      columns: 4,
      bgType: "gradient",
      bgGradient: {
        type: "linear",
        colors: [
          { color: "#4338ca", position: 0 },
          { color: "#6366f1", position: 50 },
          { color: "#818cf8", position: 100 },
        ],
        angle: 135,
      },
      textColor: "#e0e7ff",
      headingColor: "#ffffff",
      linkColor: "#c7d2fe",
      linkHoverColor: "#ffffff",
      headingSize: "base",
      headingWeight: "bold",
      socialShape: "pill",
      socialSize: "md",
      socialColorMode: "monochrome",
      socialHoverEffect: "scale",
      topBorderStyle: "none",
      dividerStyle: "none",
      shadow: "none",
      paddingTop: 64,
      paddingBottom: 40,
      bottomBarEnabled: true,
      bottomBarLayout: "centered",
      showSocialLinks: true,
      showDisclaimer: false,
      copyrightText: `© ${new Date().getFullYear()} LLCPad. All rights reserved.`,
      bottomLinks: legalLinks.slice(0, 3),
      enableAnimations: true,
      entranceAnimation: "fade-up",
      animationDuration: 400,
      widgets: [
        { type: "NEWSLETTER", title: "Join Our Newsletter", showTitle: true, column: 1, sortOrder: 0, content: { style: "inline", incentive: "Get exclusive tips and updates!" } },
        { type: "LINKS", title: "Product", showTitle: true, column: 1, sortOrder: 1, content: {}, menuItems: servicesLinks },
        { type: "LINKS", title: "Company", showTitle: true, column: 2, sortOrder: 0, content: {}, menuItems: companyLinks },
        { type: "LINKS", title: "Resources", showTitle: true, column: 3, sortOrder: 0, content: {}, menuItems: resourcesLinks },
        { type: "LINKS", title: "Legal", showTitle: true, column: 4, sortOrder: 0, content: {}, menuItems: legalLinks },
      ],
    },
  },
  {
    name: "Glassmorphism",
    description: "Trendy frosted glass effect with blur and transparency.",
    category: "modern",
    thumbnail: "/presets/footer/glassmorphism.png",
    tags: ["modern", "glass", "blur", "trendy"],
    colorPalette: {
      primary: "#1e293b",
      secondary: "#64748b",
      accent: "#0ea5e9",
      text: "#475569",
      bg: "rgba(255,255,255,0.8)",
    },
    config: {
      layout: "MULTI_COLUMN",
      columns: 4,
      bgType: "solid",
      bgColor: "rgba(248,250,252,0.95)",
      textColor: "#64748b",
      headingColor: "#1e293b",
      linkColor: "#475569",
      linkHoverColor: "#0ea5e9",
      headingSize: "sm",
      headingWeight: "semibold",
      socialShape: "rounded",
      socialSize: "md",
      socialColorMode: "brand",
      socialHoverEffect: "lift",
      topBorderStyle: "solid",
      topBorderHeight: 1,
      topBorderColor: "#e2e8f0",
      dividerStyle: "none",
      shadow: "lg",
      borderRadius: 24,
      paddingTop: 48,
      paddingBottom: 32,
      bottomBarEnabled: true,
      bottomBarLayout: "split",
      showSocialLinks: true,
      showDisclaimer: true,
      disclaimerText: "LLCPad is not a law firm and does not provide legal advice.",
      copyrightText: `© ${new Date().getFullYear()} LLCPad. All rights reserved.`,
      bottomLinks: legalLinks.slice(0, 3),
      widgets: [
        { type: "BRAND", title: "", showTitle: false, column: 1, sortOrder: 0, content: { showTagline: true, tagline: "Modern LLC formation for the digital age." } },
        { type: "SOCIAL", title: "", showTitle: false, column: 1, sortOrder: 1, content: {} },
        { type: "LINKS", title: "Quick Links", showTitle: true, column: 2, sortOrder: 0, content: {}, menuItems: servicesLinks },
        { type: "LINKS", title: "Company", showTitle: true, column: 3, sortOrder: 0, content: {}, menuItems: companyLinks },
        { type: "CONTACT", title: "Contact", showTitle: true, column: 4, sortOrder: 0, content: {} },
      ],
    },
  },
  {
    name: "Neon Tech",
    description: "Cyberpunk-inspired dark theme with neon accents and glow effects.",
    category: "modern",
    thumbnail: "/presets/footer/neon-tech.png",
    tags: ["modern", "neon", "dark", "cyberpunk"],
    colorPalette: {
      primary: "#f0abfc",
      secondary: "#a855f7",
      accent: "#22d3ee",
      text: "#c084fc",
      bg: "#0c0a1d",
    },
    config: {
      layout: "MEGA",
      columns: 5,
      bgType: "solid",
      bgColor: "#0c0a1d",
      textColor: "#a78bfa",
      headingColor: "#f0abfc",
      linkColor: "#c084fc",
      linkHoverColor: "#22d3ee",
      headingSize: "sm",
      headingWeight: "bold",
      headingStyle: "uppercase",
      socialShape: "square",
      socialSize: "lg",
      socialColorMode: "accent",
      socialHoverEffect: "glow",
      dividerStyle: "gradient",
      dividerColor: "#a855f7",
      topBorderStyle: "gradient",
      topBorderHeight: 3,
      topBorderColor: "#22d3ee",
      shadow: "none",
      paddingTop: 64,
      paddingBottom: 40,
      bottomBarEnabled: true,
      bottomBarLayout: "split",
      showSocialLinks: true,
      showDisclaimer: false,
      copyrightText: `© ${new Date().getFullYear()} LLCPad. All rights reserved.`,
      bottomLinks: legalLinks.slice(0, 3),
      enableAnimations: true,
      entranceAnimation: "fade-in",
      animationDuration: 300,
      widgets: [
        { type: "BRAND", title: "", showTitle: false, column: 1, sortOrder: 0, content: { showTagline: true, tagline: "Next-gen LLC formation." } },
        { type: "SOCIAL", title: "", showTitle: false, column: 1, sortOrder: 1, content: {} },
        { type: "LINKS", title: "Services", showTitle: true, column: 2, sortOrder: 0, content: {}, menuItems: servicesLinks },
        { type: "LINKS", title: "Company", showTitle: true, column: 3, sortOrder: 0, content: {}, menuItems: companyLinks },
        { type: "LINKS", title: "Resources", showTitle: true, column: 4, sortOrder: 0, content: {}, menuItems: resourcesLinks },
        { type: "LINKS", title: "Support", showTitle: true, column: 5, sortOrder: 0, content: {}, menuItems: supportLinks },
      ],
    },
  },

  // ============ CREATIVE CATEGORY ============
  {
    name: "Colorful Blocks",
    description: "Playful design with dotted pattern background.",
    category: "creative",
    thumbnail: "/presets/footer/colorful-blocks.png",
    tags: ["creative", "colorful", "playful", "fun"],
    colorPalette: {
      primary: "#1e293b",
      secondary: "#64748b",
      accent: "#f472b6",
      text: "#475569",
      bg: "#fef3c7",
    },
    config: {
      layout: "MULTI_COLUMN",
      columns: 4,
      bgType: "pattern",
      bgColor: "#fef3c7",
      bgPattern: "dots",
      bgPatternColor: "#f59e0b",
      bgPatternOpacity: 0.1,
      textColor: "#78716c",
      headingColor: "#292524",
      linkColor: "#57534e",
      linkHoverColor: "#f472b6",
      headingSize: "base",
      headingWeight: "bold",
      socialShape: "circle",
      socialSize: "lg",
      socialColorMode: "brand",
      socialHoverEffect: "rotate",
      dividerStyle: "dashed",
      dividerColor: "#fed7aa",
      topBorderStyle: "wave",
      topBorderHeight: 8,
      topBorderColor: "#f472b6",
      shadow: "none",
      paddingTop: 56,
      paddingBottom: 40,
      bottomBarEnabled: true,
      bottomBarLayout: "centered",
      showSocialLinks: true,
      showDisclaimer: true,
      disclaimerText: "LLCPad is not a law firm and does not provide legal advice.",
      copyrightText: `© ${new Date().getFullYear()} LLCPad. All rights reserved.`,
      bottomLinks: legalLinks.slice(0, 3),
      widgets: [
        { type: "BRAND", title: "", showTitle: false, column: 1, sortOrder: 0, content: { showTagline: true, tagline: "Making business formation fun!" } },
        { type: "SOCIAL", title: "", showTitle: false, column: 1, sortOrder: 1, content: {} },
        { type: "LINKS", title: "Explore", showTitle: true, column: 2, sortOrder: 0, content: {}, menuItems: servicesLinks },
        { type: "LINKS", title: "About", showTitle: true, column: 3, sortOrder: 0, content: {}, menuItems: companyLinks },
        { type: "NEWSLETTER", title: "Get Updates", showTitle: true, column: 4, sortOrder: 0, content: { style: "stacked" } },
      ],
    },
  },

  // ============ INDUSTRY CATEGORY ============
  {
    name: "E-commerce Pro",
    description: "Feature-rich footer for e-commerce with trust badges area.",
    category: "industry",
    thumbnail: "/presets/footer/ecommerce-pro.png",
    tags: ["industry", "ecommerce", "trust", "payments"],
    colorPalette: {
      primary: "#059669",
      secondary: "#6b7280",
      accent: "#10b981",
      text: "#4b5563",
      bg: "#f9fafb",
    },
    config: {
      layout: "MULTI_COLUMN",
      columns: 5,
      bgType: "solid",
      bgColor: "#f9fafb",
      textColor: "#6b7280",
      headingColor: "#111827",
      linkColor: "#4b5563",
      linkHoverColor: "#059669",
      headingSize: "sm",
      headingWeight: "semibold",
      socialShape: "rounded",
      socialSize: "md",
      socialColorMode: "brand",
      socialHoverEffect: "scale",
      topBorderStyle: "solid",
      topBorderHeight: 4,
      topBorderColor: "#059669",
      dividerStyle: "solid",
      dividerColor: "#e5e7eb",
      shadow: "sm",
      paddingTop: 64,
      paddingBottom: 48,
      bottomBarEnabled: true,
      bottomBarLayout: "stacked",
      showSocialLinks: true,
      showDisclaimer: true,
      disclaimerText: "LLCPad is not a law firm and does not provide legal advice.",
      copyrightText: `© ${new Date().getFullYear()} LLCPad. All rights reserved.`,
      showTrustBadges: true,
      bottomLinks: legalLinks,
      widgets: [
        { type: "BRAND", title: "", showTitle: false, column: 1, sortOrder: 0, content: { showTagline: true, tagline: "Trusted by 10,000+ businesses" } },
        { type: "CONTACT", title: "Contact Us", showTitle: true, column: 1, sortOrder: 1, content: {} },
        { type: "LINKS", title: "Services", showTitle: true, column: 2, sortOrder: 0, content: {}, menuItems: servicesLinks },
        { type: "LINKS", title: "Company", showTitle: true, column: 3, sortOrder: 0, content: {}, menuItems: companyLinks },
        { type: "LINKS", title: "Support", showTitle: true, column: 4, sortOrder: 0, content: {}, menuItems: supportLinks },
        { type: "LINKS", title: "Legal", showTitle: true, column: 5, sortOrder: 0, content: {}, menuItems: legalLinks },
      ],
    },
  },
  {
    name: "Legal Services",
    description: "Professional and trustworthy footer for legal and business services.",
    category: "industry",
    thumbnail: "/presets/footer/legal-services.png",
    tags: ["industry", "legal", "professional", "trust"],
    colorPalette: {
      primary: "#1e3a5f",
      secondary: "#64748b",
      accent: "#0369a1",
      text: "#475569",
      bg: "#ffffff",
    },
    config: {
      layout: "MULTI_COLUMN",
      columns: 4,
      bgType: "solid",
      bgColor: "#ffffff",
      textColor: "#64748b",
      headingColor: "#1e3a5f",
      linkColor: "#475569",
      linkHoverColor: "#0369a1",
      headingSize: "sm",
      headingWeight: "semibold",
      socialShape: "square",
      socialSize: "sm",
      socialColorMode: "monochrome",
      socialHoverEffect: "lift",
      topBorderStyle: "solid",
      topBorderHeight: 4,
      topBorderColor: "#1e3a5f",
      dividerStyle: "solid",
      dividerColor: "#e2e8f0",
      shadow: "none",
      paddingTop: 56,
      paddingBottom: 40,
      bottomBarEnabled: true,
      bottomBarLayout: "split",
      showSocialLinks: true,
      showDisclaimer: true,
      disclaimerText: "LLCPad is not a law firm and cannot provide legal advice. We provide self-help services at your specific direction.",
      copyrightText: `© ${new Date().getFullYear()} LLCPad. All rights reserved.`,
      bottomLinks: legalLinks,
      widgets: [
        { type: "BRAND", title: "", showTitle: false, column: 1, sortOrder: 0, content: { showTagline: true, tagline: "Professional LLC formation services" } },
        { type: "CONTACT", title: "Contact", showTitle: true, column: 1, sortOrder: 1, content: {} },
        { type: "LINKS", title: "Our Services", showTitle: true, column: 2, sortOrder: 0, content: {}, menuItems: servicesLinks },
        { type: "LINKS", title: "Company", showTitle: true, column: 3, sortOrder: 0, content: {}, menuItems: companyLinks },
        { type: "LINKS", title: "Resources", showTitle: true, column: 4, sortOrder: 0, content: {}, menuItems: resourcesLinks },
      ],
    },
  },
  {
    name: "App Launch",
    description: "App-focused footer with prominent download section.",
    category: "industry",
    thumbnail: "/presets/footer/app-launch.png",
    tags: ["industry", "app", "mobile", "download"],
    colorPalette: {
      primary: "#7c3aed",
      secondary: "#a78bfa",
      accent: "#8b5cf6",
      text: "#c4b5fd",
      bg: "#1e1b4b",
    },
    config: {
      layout: "MULTI_COLUMN",
      columns: 3,
      bgType: "gradient",
      bgGradient: {
        type: "linear",
        colors: [
          { color: "#1e1b4b", position: 0 },
          { color: "#312e81", position: 100 },
        ],
        angle: 180,
      },
      textColor: "#c4b5fd",
      headingColor: "#ffffff",
      linkColor: "#a78bfa",
      linkHoverColor: "#f5f3ff",
      headingSize: "lg",
      headingWeight: "bold",
      socialShape: "circle",
      socialSize: "lg",
      socialColorMode: "accent",
      socialHoverEffect: "scale",
      topBorderStyle: "none",
      dividerStyle: "none",
      shadow: "none",
      paddingTop: 72,
      paddingBottom: 48,
      bottomBarEnabled: true,
      bottomBarLayout: "centered",
      showSocialLinks: true,
      showDisclaimer: false,
      copyrightText: `© ${new Date().getFullYear()} LLCPad. All rights reserved.`,
      bottomLinks: legalLinks.slice(0, 3),
      enableAnimations: true,
      entranceAnimation: "slide-up",
      animationDuration: 400,
      widgets: [
        { type: "BRAND", title: "", showTitle: false, column: 1, sortOrder: 0, content: { showTagline: true, tagline: "Download our app and start your business today" } },
        { type: "SOCIAL", title: "Follow Us", showTitle: true, column: 1, sortOrder: 1, content: {} },
        { type: "LINKS", title: "Company", showTitle: true, column: 2, sortOrder: 0, content: {}, menuItems: companyLinks },
        { type: "LINKS", title: "Support", showTitle: true, column: 3, sortOrder: 0, content: {}, menuItems: supportLinks },
      ],
    },
  },
  {
    name: "Newsletter First",
    description: "Newsletter-focused footer with large signup form as the hero element.",
    category: "industry",
    thumbnail: "/presets/footer/newsletter-first.png",
    tags: ["industry", "newsletter", "marketing", "cta"],
    colorPalette: {
      primary: "#dc2626",
      secondary: "#6b7280",
      accent: "#ef4444",
      text: "#4b5563",
      bg: "#fef2f2",
    },
    config: {
      layout: "NEWSLETTER_HERO",
      columns: 4,
      bgType: "solid",
      bgColor: "#fef2f2",
      textColor: "#6b7280",
      headingColor: "#1f2937",
      linkColor: "#4b5563",
      linkHoverColor: "#dc2626",
      accentColor: "#dc2626",
      headingSize: "xl",
      headingWeight: "bold",
      socialShape: "circle",
      socialSize: "md",
      socialColorMode: "brand",
      socialHoverEffect: "scale",
      topBorderStyle: "none",
      dividerStyle: "solid",
      dividerColor: "#fecaca",
      shadow: "none",
      paddingTop: 80,
      paddingBottom: 48,
      bottomBarEnabled: true,
      bottomBarLayout: "split",
      showSocialLinks: false, // Using SOCIAL widget instead
      showDisclaimer: true,
      disclaimerText: "LLCPad is not a law firm and does not provide legal advice.",
      copyrightText: `© ${new Date().getFullYear()} LLCPad. All rights reserved.`,
      bottomLinks: legalLinks,
      newsletterEnabled: true,
      newsletterTitle: "Stay in the loop",
      newsletterSubtitle: "Get the latest updates, tips, and exclusive offers delivered to your inbox.",
      widgets: [
        // NEWSLETTER widget for hero section - edit title and subtitle from Widget Areas (column 1)
        // Note: In NEWSLETTER_HERO layout, this widget's content is used for the hero section
        { type: "NEWSLETTER", title: "Stay in the loop", showTitle: true, column: 1, sortOrder: 0, content: { subtitle: "Get the latest updates, tips, and exclusive offers delivered to your inbox.", buttonText: "Subscribe" } },
        { type: "BRAND", title: "", showTitle: false, column: 1, sortOrder: 1, content: { showTagline: true, tagline: "Your trusted LLC formation partner" } },
        { type: "SOCIAL", title: "", showTitle: false, column: 1, sortOrder: 2, content: {} },
        { type: "LINKS", title: "Services", showTitle: true, column: 2, sortOrder: 0, content: {}, menuItems: servicesLinks },
        { type: "LINKS", title: "Company", showTitle: true, column: 3, sortOrder: 0, content: {}, menuItems: companyLinks },
        { type: "LINKS", title: "Support", showTitle: true, column: 4, sortOrder: 0, content: {}, menuItems: supportLinks },
      ],
    },
  },

  // ============ NEW PRESETS (Matching User Screenshots) ============

  // Screenshot 1: Dark with Newsletter + Payment Icons + Purple Bottom Gradient
  {
    name: "Dark Newsletter Pro",
    description: "Modern dark footer with newsletter signup, social icons, and payment methods. Features a beautiful purple gradient at the bottom.",
    category: "modern",
    thumbnail: "/presets/footer/dark-newsletter-pro.png",
    tags: ["dark", "newsletter", "payments", "gradient", "modern"],
    colorPalette: {
      primary: "#ffffff",
      secondary: "#9ca3af",
      accent: "#a855f7",
      text: "#9ca3af",
      bg: "#000000",
    },
    config: {
      layout: "MULTI_COLUMN",
      columns: 3,
      bgType: "solid",
      bgColor: "#000000",
      textColor: "#9ca3af",
      headingColor: "#ffffff",
      linkColor: "#d1d5db",
      linkHoverColor: "#a855f7",
      headingSize: "base",
      headingWeight: "semibold",
      socialShape: "circle",
      socialSize: "md",
      socialColorMode: "monochrome",
      socialHoverEffect: "scale",
      topBorderStyle: "none",
      dividerStyle: "none",
      shadow: "none",
      borderRadius: 24,
      paddingTop: 64,
      paddingBottom: 48,
      bottomBarEnabled: true,
      bottomBarLayout: "split",
      showSocialLinks: true,
      showDisclaimer: false,
      copyrightText: `© ${new Date().getFullYear()} LLCPad Inc. All Rights Reserved.`,
      bottomLinks: legalLinks.slice(0, 2),
      widgets: [
        { type: "BRAND", title: "", showTitle: false, column: 1, sortOrder: 0, content: { showTagline: true, tagline: "Sign up for insider news, feature launches, and tips to scale faster." } },
        { type: "NEWSLETTER", title: "", showTitle: false, column: 1, sortOrder: 1, content: { style: "inline", placeholder: "Email" } },
        { type: "SOCIAL", title: "", showTitle: false, column: 1, sortOrder: 2, content: {} },
        { type: "LINKS", title: "Quick Links", showTitle: true, column: 2, sortOrder: 0, content: {}, menuItems: [
          { label: "Products", url: "/products", target: "_self" },
          { label: "About Us", url: "/about", target: "_self" },
          { label: "Case Studies", url: "/case-studies", target: "_self" },
          { label: "Blog", url: "/blog", target: "_self" },
        ]},
        { type: "LINKS", title: "Resources", showTitle: true, column: 3, sortOrder: 0, content: {}, menuItems: [
          { label: "Help Center", url: "/help", target: "_self" },
          { label: "Documentation", url: "/docs", target: "_self" },
          { label: "Terms & Conditions", url: "/terms", target: "_self" },
          { label: "Privacy Policy", url: "/privacy", target: "_self" },
          { label: "FAQs", url: "/faq", target: "_self" },
        ]},
      ],
    },
  },

  // Screenshot 2: Light Purple SaaS with Left Border Accent
  {
    name: "SaaS Lavender",
    description: "Clean light purple footer with a modern left border accent and CTA button. Perfect for SaaS products.",
    category: "modern",
    thumbnail: "/presets/footer/saas-lavender.png",
    tags: ["light", "purple", "saas", "modern", "cta"],
    colorPalette: {
      primary: "#1e1b4b",
      secondary: "#6366f1",
      accent: "#7c3aed",
      text: "#4b5563",
      bg: "#f5f3ff",
    },
    config: {
      layout: "MULTI_COLUMN",
      columns: 4,
      bgType: "solid",
      bgColor: "#f5f3ff",
      textColor: "#6b7280",
      headingColor: "#1e1b4b",
      linkColor: "#4b5563",
      linkHoverColor: "#7c3aed",
      headingSize: "base",
      headingWeight: "semibold",
      socialShape: "circle",
      socialSize: "sm",
      socialColorMode: "monochrome",
      socialHoverEffect: "scale",
      topBorderStyle: "none",
      dividerStyle: "none",
      shadow: "none",
      borderRadius: 16,
      paddingTop: 56,
      paddingBottom: 40,
      bottomBarEnabled: false,
      showSocialLinks: true,
      showDisclaimer: false,
      copyrightText: "",
      bottomLinks: [],
      widgets: [
        { type: "BRAND", title: "", showTitle: false, column: 1, sortOrder: 0, content: { showTagline: true, tagline: "Write Smarter with AI.", showCTA: true, ctaText: "Unlock AI Copy", ctaUrl: "/signup", ctaIcon: "sparkles" } },
        { type: "SOCIAL", title: "", showTitle: false, column: 1, sortOrder: 1, content: {} },
        { type: "LINKS", title: "Product & Features", showTitle: true, column: 2, sortOrder: 0, content: {}, menuItems: [
          { label: "Key Features", url: "/features", target: "_self" },
          { label: "Multilingual Support", url: "/features/multilingual", target: "_self" },
          { label: "Integrated Solutions", url: "/integrations", target: "_self" },
          { label: "AI Copy Generator", url: "/ai-copy", target: "_self" },
          { label: "Smart Personalization", url: "/personalization", target: "_self" },
        ]},
        { type: "LINKS", title: "Company & Resources", showTitle: true, column: 3, sortOrder: 0, content: {}, menuItems: [
          { label: "About Us", url: "/about", target: "_self" },
          { label: "Case Studies", url: "/case-studies", target: "_self" },
          { label: "Affiliate Program", url: "/affiliates", target: "_self" },
          { label: "AI & Copywriting Blog", url: "/blog", target: "_self" },
          { label: "Webinars & Tutorials", url: "/webinars", target: "_self" },
          { label: "Press & Media", url: "/press", target: "_self" },
          { label: "Careers", url: "/careers", target: "_self" },
        ]},
        { type: "LINKS", title: "Support & Legal", showTitle: true, column: 4, sortOrder: 0, content: {}, menuItems: [
          { label: "Help Center", url: "/help", target: "_self" },
          { label: "Contact Support", url: "/contact", target: "_self" },
          { label: "Terms of Service", url: "/terms", target: "_self" },
          { label: "Privacy Policy", url: "/privacy", target: "_self" },
          { label: "GDPR Compliance", url: "/gdpr", target: "_self" },
          { label: "Security & Compliance", url: "/security", target: "_self" },
        ]},
      ],
    },
  },

  // Screenshot 3: Dark Gradient Mesh - App/Landing Focus
  {
    name: "Gradient Mesh Hero",
    description: "Stunning dark footer with colorful gradient mesh background. Features centered branding with CTA buttons - perfect for app landing pages.",
    category: "creative",
    thumbnail: "/presets/footer/gradient-mesh-hero.png",
    tags: ["dark", "gradient", "mesh", "hero", "app", "landing"],
    colorPalette: {
      primary: "#ffffff",
      secondary: "#9ca3af",
      accent: "#06b6d4",
      text: "#9ca3af",
      bg: "#0a0a0a",
    },
    config: {
      layout: "CENTERED",
      columns: 1,
      bgType: "gradient",
      bgGradient: {
        type: "radial",
        colors: [
          { color: "#1e1b4b", position: 0 },
          { color: "#0f172a", position: 30 },
          { color: "#0a0a0a", position: 100 },
        ],
        angle: 0,
      },
      textColor: "#9ca3af",
      headingColor: "#ffffff",
      linkColor: "#d1d5db",
      linkHoverColor: "#06b6d4",
      headingSize: "3xl",
      headingWeight: "bold",
      socialShape: "circle",
      socialSize: "lg",
      socialColorMode: "monochrome",
      socialHoverEffect: "glow",
      topBorderStyle: "none",
      dividerStyle: "none",
      shadow: "none",
      paddingTop: 96,
      paddingBottom: 64,
      bottomBarEnabled: false,
      showSocialLinks: true,
      showDisclaimer: false,
      copyrightText: "",
      bottomLinks: [],
      enableAnimations: true,
      entranceAnimation: "fade-up",
      animationDuration: 500,
      widgets: [
        { type: "BRAND", title: "", showTitle: false, column: 1, sortOrder: 0, content: {
          showTagline: true,
          tagline: "Your Next High-Performing Landing Page Starts Here!",
          subtitle: "Try it free for 14 days – no credit card required. Get started today and see why thousands of marketers and startups love our AI-powered builder.",
          showCTA: true,
          ctaText: "Install for Free",
          ctaUrl: "/signup",
          secondaryCTA: true,
          secondaryCtaText: "See Live Examples",
          secondaryCtaUrl: "/examples"
        }},
        { type: "SOCIAL", title: "", showTitle: false, column: 1, sortOrder: 1, content: {} },
      ],
    },
  },

  // Screenshot 4: Light with Grid Pattern
  {
    name: "Clean Grid",
    description: "Minimalist light footer with subtle grid pattern background. Clean and professional for any business.",
    category: "minimal",
    thumbnail: "/presets/footer/clean-grid.png",
    tags: ["light", "grid", "minimal", "clean", "professional"],
    colorPalette: {
      primary: "#1e293b",
      secondary: "#64748b",
      accent: "#6366f1",
      text: "#64748b",
      bg: "#ffffff",
    },
    config: {
      layout: "MULTI_COLUMN",
      columns: 4,
      bgType: "pattern",
      bgColor: "#ffffff",
      bgPattern: "grid",
      bgPatternColor: "#e2e8f0",
      bgPatternOpacity: 50,
      textColor: "#64748b",
      headingColor: "#1e293b",
      linkColor: "#475569",
      linkHoverColor: "#6366f1",
      headingSize: "base",
      headingWeight: "semibold",
      socialShape: "circle",
      socialSize: "sm",
      socialColorMode: "monochrome",
      socialHoverEffect: "scale",
      topBorderStyle: "none",
      dividerStyle: "solid",
      dividerColor: "#e2e8f0",
      shadow: "none",
      paddingTop: 56,
      paddingBottom: 40,
      bottomBarEnabled: true,
      bottomBarLayout: "centered",
      showSocialLinks: true,
      showDisclaimer: false,
      copyrightText: `Copyright © LLCPad ${new Date().getFullYear()}`,
      bottomLinks: [],
      widgets: [
        { type: "BRAND", title: "", showTitle: false, column: 1, sortOrder: 0, content: { showTagline: true, tagline: "Helping you grow smarter, faster with AI-powered tools." } },
        { type: "SOCIAL", title: "", showTitle: false, column: 1, sortOrder: 1, content: {} },
        { type: "LINKS", title: "Product", showTitle: true, column: 2, sortOrder: 0, content: {}, menuItems: [
          { label: "Features", url: "/features", target: "_self" },
          { label: "Integrations", url: "/integrations", target: "_self" },
          { label: "Templates", url: "/templates", target: "_self" },
          { label: "Pricing Plans", url: "/pricing", target: "_self" },
          { label: "Contact", url: "/contact", target: "_self" },
        ]},
        { type: "LINKS", title: "Company", showTitle: true, column: 3, sortOrder: 0, content: {}, menuItems: [
          { label: "About Us", url: "/about", target: "_self" },
          { label: "Meet Our Team", url: "/team", target: "_self" },
          { label: "Blog / Insights", url: "/blog", target: "_self" },
          { label: "FAQs", url: "/faq", target: "_self" },
        ]},
        { type: "LINKS", title: "Legal & Support", showTitle: true, column: 4, sortOrder: 0, content: {}, menuItems: [
          { label: "Terms & Conditions", url: "/terms", target: "_self" },
          { label: "Privacy Policy", url: "/privacy", target: "_self" },
          { label: "Cookie Policy", url: "/cookies", target: "_self" },
          { label: "Help Center", url: "/help", target: "_self" },
        ]},
      ],
    },
  },
];

// POST - Seed footer presets
export async function POST() {
  try {
    const accessCheck = await checkAdminOnly();
    if ("error" in accessCheck) {
      return authError(accessCheck);
    }

    let created = 0;
    let updated = 0;

    for (const preset of footerPresets) {
      const existing = await prisma.footerPreset.findFirst({
        where: { name: preset.name, isBuiltIn: true },
      });

      if (existing) {
        await prisma.footerPreset.update({
          where: { id: existing.id },
          data: {
            ...preset,
            isBuiltIn: true,
            isPublic: true,
          },
        });
        updated++;
      } else {
        await prisma.footerPreset.create({
          data: {
            ...preset,
            isBuiltIn: true,
            isPublic: true,
          },
        });
        created++;
      }
    }

    return NextResponse.json({
      success: true,
      message: `Seeded ${created} new presets, updated ${updated} existing presets`,
      total: footerPresets.length,
    });
  } catch (error) {
    console.error("Error seeding footer presets:", error);
    return NextResponse.json(
      { error: "Failed to seed presets" },
      { status: 500 }
    );
  }
}
